(function(){'use strict';const C=StudioCore,A=StudioAudio,$=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));let project=C.defaultProject(),activeTrack=0,selected=-1,history=[],future=[],textTimer,context,source,gain,playToken=0,playInfo=null,frame=0,sfxCache=null,localOk=true;const STORAGE='numbered-music-studio-v1';
const notice=(s,bad=false)=>{$('notice').textContent=s;$('notice').classList.toggle('bad',bad);};const track=()=>project.tracks[activeTrack];function saveLocal(){try{localStorage.setItem(STORAGE,JSON.stringify(project));localOk=true;$('autosave').textContent='已自动保存到此浏览器';}catch(e){localOk=false;$('autosave').textContent='此浏览器未允许自动保存，请手动保存工程';}}
function validateInstruments(p){for(const t of p.tracks)if(!A.instruments.some(i=>i.id===t.instrument))throw Error('未知音色：'+t.instrument);return p;}
try{let stored=localStorage.getItem(STORAGE);if(stored)project=validateInstruments(C.cleanProject(JSON.parse(stored)));}catch(e){notice('已打开新工程。之前的本机草稿无法读取，请使用保存的 JSON 工程。',true);}
function remember(){history.push(clone(project));if(history.length>100)history.shift();future=[];}
function commit(fn,full=true){stop();remember();fn();selected=-1;sfxCache=null;saveLocal();if(full)render();else renderUndo();}
function renderUndo(){$('undo').disabled=!history.length;$('redo').disabled=!future.length;}
function changeHistory(redo){flushText();let from=redo?future:history,to=redo?history:future;if(!from.length)return;stop();to.push(clone(project));project=from.pop();activeTrack=Math.min(activeTrack,project.tracks.length-1);selected=-1;sfxCache=null;saveLocal();render();}
function flushText(){if(textTimer){clearTimeout(textTimer);textTimer=null;saveLocal();}}
function el(tag,text,cls){let e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function render(){activeTrack=Math.min(activeTrack,project.tracks.length-1);$('title').value=project.title;$('bpm').value=project.bpm;$('key').value=project.key;$('volume').value=project.volume;$('volumeValue').textContent=Math.round(project.volume*100)+'%';$('loop').checked=project.loop;$('tracks').replaceChildren();project.tracks.forEach((t,i)=>{let b=el('button',undefined,'track'+(i===activeTrack?' selected':''));b.append(el('strong',(i+1)+'. '+t.name),el('small',(t.mute?'已静音 · ':'')+(A.instruments.find(x=>x.id===t.instrument)?.name||t.instrument)));b.onclick=()=>{flushText();activeTrack=i;selected=-1;render();};$('tracks').append(b);});$('addTrack').disabled=project.tracks.length>=4;$('removeTrack').disabled=project.tracks.length<=1;$('trackName').value=track().name;$('instrument').value=track().instrument;$('instrumentDescription').textContent=A.instruments.find(i=>i.id===track().instrument)?.description||'';$('trackVolume').value=track().volume;$('trackMute').checked=track().mute;$('notation').value=track().notation;renderNotes();renderSfx();renderTone();renderUndo();}
function renderNotes(){let parsed;try{parsed=C.parse(track().notation,project.key);$('parseError').textContent='';$('stats').textContent=parsed.events.length+' 个音符 / '+Number(parsed.totalBeats.toFixed(3))+' 拍 / '+(parsed.totalBeats*60/project.bpm).toFixed(1)+' 秒';}catch(e){$('parseError').textContent=e.message;$('stats').textContent='请修正乐谱';$('timeline').replaceChildren();return;}$('timeline').replaceChildren();parsed.events.forEach(e=>{let b=el('button',undefined,'note'+(!e.pitches.length?' rest':'')+(selected===e.index?' chosen':''));b.style.width=Math.max(54,Math.min(240,e.duration*54))+'px';b.dataset.index=e.index;b.append(el('span',e.token),el('small',e.duration+' 拍'));b.onclick=()=>{selected=e.index;$('notation').focus();$('notation').setSelectionRange(e.start,e.end);renderNotes();};$('timeline').append(b);});let e=parsed.events[selected];$('selectedLabel').textContent=e?'已选第 '+(selected+1)+' 个音符':'尚未选中音符';$('eventToken').value=e?e.token:'';$('applyEvent').disabled=!e;$('deleteEvent').disabled=!e;}
function insertToken(token){let t=$('notation'),start=t.selectionStart,end=t.selectionEnd;commit(()=>{let before=track().notation.slice(0,start),after=track().notation.slice(end);track().notation=before+(before&&!/\s$/.test(before)?' ':'')+token+' '+after;});t.focus();let at=start+token.length+1+(start&&!/\s/.test(track().notation[start-1])?1:0);t.setSelectionRange(at,at);}
function selectedEvent(){return C.parse(track().notation,project.key).events[selected];}
function audioContext(){if(!context){let AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('此浏览器不支持音频播放，请使用新版 Edge 或 Chrome');context=new AC();gain=context.createGain();gain.connect(context.destination);}return context;}
function stop(){playToken++;if(source){try{source.stop();}catch(e){}source.disconnect();source=null;}playInfo=null;cancelAnimationFrame(frame);document.querySelectorAll('.note.active').forEach(e=>e.classList.remove('active'));$('play').textContent='▶ 播放旋律';}
async function playPcm(result,kind,token){const ctx=audioContext();await ctx.resume();if(token!==playToken)return;let buffer=ctx.createBuffer(1,result.samples.length,result.sampleRate||44100);buffer.copyToChannel(result.samples,0);source=ctx.createBufferSource();source.buffer=buffer;source.connect(gain);gain.gain.value=1;source.loop=kind==='music'&&project.loop;if(kind==='music'&&result.musicalDuration>0)source.loopEnd=result.musicalDuration;source.start();playInfo={kind,start:ctx.currentTime,result};source.onended=()=>{if(token!==playToken)return;source=null;playInfo=null;$('play').textContent='▶ 播放旋律';document.querySelectorAll('.note.active').forEach(e=>e.classList.remove('active'));};if(kind==='music'){$('play').textContent='♫ 正在播放';animate();}}
function animate(){if(!playInfo||playInfo.kind!=='music')return;let t=context.currentTime-playInfo.start;if(project.loop)t%=playInfo.result.musicalDuration||playInfo.result.samples.length/(playInfo.result.sampleRate||44100);let ids=new Set(playInfo.result.events.filter(e=>e.track===activeTrack&&t>=e.start&&t<e.start+e.duration).map(e=>e.index));document.querySelectorAll('#timeline .note').forEach(e=>e.classList.toggle('active',ids.has(Number(e.dataset.index))));frame=requestAnimationFrame(animate);}
function validateMusic(){for(let i=0;i<project.tracks.length;i++){try{C.parse(project.tracks[i].notation,project.key);}catch(e){activeTrack=i;render();$('notation').focus();if(Number.isInteger(e.position))$('notation').setSelectionRange(e.position,e.position+1);throw Error('音轨 '+(i+1)+'：'+e.message);}}}
async function playMusic(){flushText();stop();let token=playToken;try{validateMusic();audioContext();await context.resume();notice('正在准备声音…');let result=await A.renderMusic(clone(project),44100);if(token!==playToken)return;await playPcm(result,'music',token);if(token!==playToken)return;notice('正在播放。点时间线可查看音符，停止后再修改。');}catch(e){if(token===playToken)notice(e.message,true);}}
function download(bytes,name,type){let blob=new Blob([bytes],{type}),url=URL.createObjectURL(blob),link=el('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function safeName(){return (project.title.trim()||'七音工程').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,80);}
async function exportMusic(midi){flushText();try{validateMusic();if(midi){download(C.toMidi(project),safeName()+'.mid','audio/midi');notice('已生成 MIDI，只保留音符、节拍和基本乐器；音色细调与独立音效请用 WAV 保留。音色由打开它的软件决定。');}else{notice('正在渲染 WAV，请稍候…');$('wav').disabled=true;let r=await A.renderMusic(clone(project),44100);download(A.encodeWav(r.samples,r.sampleRate||44100),safeName()+'.wav','audio/wav');notice('WAV 已生成。发布使用采样音色的作品时，请保留随附素材署名。');}}catch(e){notice(e.message,true);}finally{$('wav').disabled=false;}}
const sfxDefs=[['frequency','起始音高',40,4000,1,'Hz'],['endFrequency','结束音高',20,8000,1,'Hz'],['duration','声音时长',.05,4,.01,'秒'],['attack','渐入',.001,1,.001,'秒'],['decay','衰减',.01,3,.01,'秒'],['noise','噪声比例',0,1,.01,''],['filter','低通滤波',100,20000,100,'Hz'],['volume','音量',0,1,.01,'']];const presetNames={coin:'✦ 金币',jump:'↗ 跳跃',laser:'⌁ 激光',explosion:'✹ 爆炸',hit:'◆ 打击',whoosh:'≈ 挥动'};
function renderSfx(){for(const [key]of sfxDefs){$('sfx_'+key).value=project.sfx[key];$('sfxValue_'+key).textContent=project.sfx[key];}$('sfxWave').value=project.sfx.wave;document.querySelectorAll('#presets button').forEach(b=>b.classList.toggle('active',b.dataset.preset===project.sfx.preset));try{sfxCache=A.renderSfx(project.sfx,44100);$('sfxDuration').textContent=(sfxCache.samples.length/44100).toFixed(2)+' 秒';drawWave(sfxCache.samples);}catch(e){notice(e.message,true);}}
function drawWave(samples){const canvas=$('waveform'),ctx=canvas.getContext('2d');if(!ctx)return;let w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#466759';ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();ctx.strokeStyle='#d9e9a5';ctx.beginPath();for(let x=0;x<w;x++){let a=Math.floor(x*samples.length/w),b=Math.max(a+1,Math.floor((x+1)*samples.length/w)),lo=0,hi=0;for(let i=a;i<b;i++){lo=Math.min(lo,samples[i]||0);hi=Math.max(hi,samples[i]||0);}ctx.moveTo(x,h/2+lo*h*.46);ctx.lineTo(x,h/2+hi*h*.46);}ctx.stroke();}
const toneDefs=[['startSemitones','起始音高偏移',-24,24,1,'半音'],['endSemitones','结束音高偏移',-24,24,1,'半音'],['gateRatio','发声占音长比例',.1,1,.01,''],['attack','渐入',.001,1,.001,'秒'],['decay','衰减',.01,3,.01,'秒'],['noise','噪声比例',0,1,.01,''],['filter','低通滤波',100,20000,100,'Hz'],['volume','效果音量',0,1,.01,'']];
function toneDefaults(){return window.StudioTone?window.StudioTone.defaults():{enabled:false,startSemitones:0,endSemitones:0,gateRatio:.94,attack:.005,decay:.25,noise:0,filter:20000,volume:1,seed:42};}
function renderTone(){const value=track().tone||toneDefaults();$('toneEnabled').checked=!!value.enabled;for(const [key]of toneDefs){$('tone_'+key).value=value[key];$('tone_'+key).disabled=!value.enabled;$('toneValue_'+key).textContent=value[key];}}
for(const [key,label,min,max,step,unit]of toneDefs){const l=el('label'),name=el('span',label+' '),output=el('output'),input=el('input');output.id='toneValue_'+key;name.append(output,document.createTextNode(' '+unit));input.id='tone_'+key;input.type='range';input.min=min;input.max=max;input.step=step;l.append(name,input);$('toneControls').append(l);input.oninput=()=>{output.textContent=input.value;};input.onchange=()=>{const value=Number(input.value);if(!Number.isFinite(value)||value<min||value>max){notice(label+' 超出范围',true);renderTone();return;}commit(()=>{track().tone={...(track().tone||toneDefaults()),[key]:value};},false);renderTone();};}
$('toneEnabled').onchange=e=>{commit(()=>{track().tone={...(track().tone||toneDefaults()),enabled:e.target.checked};},false);renderTone();};
for(const [key,label,min,max,step,unit]of sfxDefs){let l=el('label'),name=el('span',label+' '),output=el('output');output.id='sfxValue_'+key;name.append(output,document.createTextNode(' '+unit));let input=el('input');input.id='sfx_'+key;input.type=key==='seed'?'number':'range';input.min=min;input.max=max;input.step=step;l.append(name,input);$('sfxControls').append(l);input.oninput=()=>{output.textContent=input.value;};input.onchange=()=>{let n=Number(input.value);if(!Number.isFinite(n)||n<min||n>max){notice(label+' 超出范围',true);renderSfx();return;}commit(()=>{project.sfx[key]=n;project.sfx.preset='custom';},false);renderSfx();};}
for(const [id,name]of Object.entries(presetNames)){let b=el('button',name);b.dataset.preset=id;b.onclick=()=>commit(()=>{project.sfx={...project.sfx,...clone(A.sfxPresets[id]),preset:id};delete project.sfx.name;});$('presets').append(b);}
$('sfxWave').onchange=e=>{commit(()=>{project.sfx.wave=e.target.value;project.sfx.preset='custom';},false);renderSfx();};$('playSfx').onclick=async()=>{stop();let token=playToken;try{let r=A.renderSfx(project.sfx,44100);await playPcm(r,'sfx',token);if(token!==playToken)return;notice('正在试听音效。');}catch(e){notice(e.message,true);}};$('stopSfx').onclick=stop;$('exportSfx').onclick=()=>{try{let r=A.renderSfx(project.sfx,44100);download(A.encodeWav(r.samples,r.sampleRate||44100),safeName()+'-'+project.sfx.preset+'.wav','audio/wav');notice('音效 WAV 已生成，请查看浏览器下载。');}catch(e){notice(e.message,true);}};
C.KEYS.forEach((k,i)=>{let o=el('option',k);o.value=i;$('key').append(o);});A.instruments.forEach(i=>{let o=el('option',i.name);o.value=i.id;$('instrument').append(o);});['do','re','mi','fa','sol','la','ti','休止'].forEach((name,i)=>{let n=i===7?0:i+1,b=el('button');b.append(el('b',String(n)),el('small',name));b.onclick=()=>insertToken((n?$('accidental').value:'')+n+(n?$('octave').value:'')+$('duration').value);$('keyboard').append(b);});document.querySelectorAll('[data-chord]').forEach(b=>b.onclick=()=>{let chars=b.dataset.chord.match(/[1-7]'?/g).map(n=>$('accidental').value+n+$('octave').value);insertToken('['+chars.join(' ')+']'+$('duration').value);});$('bar').onclick=()=>insertToken('|');
$('notation').oninput=()=>{stop();if(!textTimer)remember();track().notation=$('notation').value;selected=-1;clearTimeout(textTimer);textTimer=setTimeout(()=>{textTimer=null;saveLocal();},600);renderNotes();renderUndo();};$('notation').onblur=flushText;
$('applyEvent').onclick=()=>{try{let token=$('eventToken').value.trim(),parsed=C.parse(token,project.key);if(parsed.events.length!==1)throw Error('这里请输入一个音符或一个和弦');let e=selectedEvent();commit(()=>{track().notation=track().notation.slice(0,e.start)+token+track().notation.slice(e.end);});}catch(e){notice(e.message,true);}};$('deleteEvent').onclick=()=>{try{let e=selectedEvent();commit(()=>{track().notation=track().notation.slice(0,e.start)+track().notation.slice(e.end);});}catch(e){notice(e.message,true);}};$('deselect').onclick=()=>{selected=-1;renderNotes();};
$('title').onchange=e=>commit(()=>{project.title=e.target.value.slice(0,100);});$('bpm').onchange=e=>{let n=Number(e.target.value);if(!Number.isFinite(n)||n<40||n>240){notice('速度须在 40 到 240 BPM 之间',true);render();return;}commit(()=>{project.bpm=n;});};$('key').onchange=e=>commit(()=>{project.key=Number(e.target.value);});$('volume').oninput=e=>{$('volumeValue').textContent=Math.round(Number(e.target.value)*100)+'%';};$('volume').onchange=e=>commit(()=>{project.volume=Number(e.target.value);});$('loop').onchange=e=>{remember();project.loop=e.target.checked;if(source&&playInfo?.kind==='music')source.loop=project.loop;saveLocal();renderUndo();};$('trackName').onchange=e=>commit(()=>{track().name=e.target.value.slice(0,40)||'音轨';});$('instrument').onchange=e=>commit(()=>{track().instrument=e.target.value;});$('trackVolume').onchange=e=>commit(()=>{track().volume=Number(e.target.value);});$('trackMute').onchange=e=>commit(()=>{track().mute=e.target.checked;});$('addTrack').onclick=()=>{if(project.tracks.length<4)commit(()=>{project.tracks.push({name:'音轨 '+(project.tracks.length+1),instrument:'piano',volume:.6,mute:false,notation:''});activeTrack=project.tracks.length-1;});};$('removeTrack').onclick=()=>{if(project.tracks.length>1)commit(()=>{project.tracks.splice(activeTrack,1);activeTrack=Math.max(0,activeTrack-1);});};
const templates={original:'1 2 3 5 | 6 5 3:2 | 4 3 2 1 | 2 5 1:2',scale:"1 2 3 4 5 6 7 1':2 | 7 6 5 4 3 2 1:2",chords:'[135]:4 | [461\']:4 | [572\']:4 | [135]:4',twinkle:'1 1 5 5 | 6 6 5:2 | 4 4 3 3 | 2 2 1:2'};$('loadTemplate').onclick=()=>{let val=$('template').value;if(!val)return notice('先选择一个范例。');commit(()=>{track().notation=templates[val];});notice('范例已放入当前音轨，可以撤销。');};
$('undo').onclick=()=>changeHistory(false);$('redo').onclick=()=>changeHistory(true);$('play').onclick=playMusic;$('stop').onclick=stop;$('wav').onclick=()=>exportMusic(false);$('midi').onclick=()=>exportMusic(true);$('save').onclick=()=>{flushText();download(JSON.stringify(project,null,2),safeName()+'.json','application/json');notice('工程已生成，请查看浏览器下载。');};$('open').onclick=()=>{$('file').value='';$('file').click();};$('file').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>200000)throw Error('工程文件超过 200 KB 上限');let p=validateInstruments(C.cleanProject(JSON.parse(await f.text())));commit(()=>{project=p;activeTrack=0;});notice('已打开工程。原来的工程可以通过撤销恢复。');}catch(e){notice('无法打开：'+e.message,true);}};
function showWorkspace(tab){stop();for(const t of ['score','transcription','music','sfx','advanced','help']){$(t+'Panel').hidden=t!==tab;$(t+'Tab').classList.toggle('active',t===tab);$(t+'Tab').setAttribute('aria-selected',t===tab?'true':'false');}$('compositionToolbar').hidden=['transcription','score'].includes(tab);if(tab==='sfx')drawWave(sfxCache?.samples||[]);window.dispatchEvent(new CustomEvent('studio:workspace',{detail:{tab}}));}for(const tab of ['score','transcription','music','sfx','advanced','help'])$(tab+'Tab').onclick=()=>showWorkspace(tab);
$('advancedMidi').onclick=()=>exportMusic(true);$('launchAdvanced').onclick=(event)=>{flushText();stop();saveLocal();if(!localOk&&!window.confirm('此浏览器无法自动保存当前简谱与音效。请先点“保存工程”下载 JSON。仍要离开此页？'))event.preventDefault();};
document.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey))return;if(!$('transcriptionPanel').hidden||!$('scorePanel').hidden)return;const typing=['INPUT','TEXTAREA'].includes(document.activeElement.tagName);if(e.key.toLowerCase()==='s'){e.preventDefault();$('save').click();}else if(!typing&&(e.key.toLowerCase()==='z'||e.key.toLowerCase()==='y')){e.preventDefault();changeHistory(e.shiftKey||e.key.toLowerCase()==='y');}});window.addEventListener('beforeunload',flushText);render();window.StudioApp={showWorkspace,getProject:()=>clone(project),stop,playMusic,getPlayback:()=>playInfo,importProject:p=>{const clean=validateInstruments(C.cleanProject(p));commit(()=>{project=clean;activeTrack=0;});}};
})();
