/* Numbered Music Studio, original application code. */
(function(root){'use strict';
const MAX_BEATS=180,MAX_NOTES=1000,KEYS=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'];
function fail(message,source,pos){const before=source.slice(0,pos);let e=new Error(message+'（第 '+(before.split('\n').length)+' 行，第 '+(pos-before.lastIndexOf('\n'))+' 列）');e.position=pos;e.line=before.split('\n').length;e.column=pos-before.lastIndexOf('\n');throw e;}
function parse(source,key=0){if(typeof source!=='string'||source.length>12000)throw new Error('乐谱需为文字，最多 12000 字符');if(!Number.isInteger(key)||key<0||key>11)throw new Error('调性超出范围');let i=0,beat=0,events=[];const scale=[0,2,4,5,7,9,11];function pitch(){let accidental=0;if(source[i]==='#'){accidental=1;i++;}else if(source[i]==='b'){accidental=-1;i++;}let n=source[i++];if(!/[0-7]/.test(n||'')||!n)fail('这里需要 0 到 7 的数字音符',source,i-1);let oct=0;while(source[i]==="'"||source[i]===','){oct+=source[i++]==="'"?1:-1;}if(Math.abs(oct)>2)fail('最多升高或降低两个八度',source,i-1);if(n==='0'&&(oct||accidental))fail('休止符 0 不能升降音',source,i-1);return n==='0'?null:60+Number(key)+scale[Number(n)-1]+12*oct+accidental;}
while(i<source.length){if(/[\s|；;]/.test(source[i])){i++;continue;}let start=i,pitches=[];if(source[i]==='['){i++;while(i<source.length&&source[i]!==']'){if(/\s/.test(source[i])){i++;continue;}let p=pitch();if(p===null)fail('和弦里不能放休止符 0',source,i-1);pitches.push(p);if(pitches.length>8)fail('一个和弦最多 8 个音',source,i-1);}if(source[i]!==']'||!pitches.length)fail('和弦需要成对的 [ ]，且至少一个音',source,start);i++;}else{let p=pitch();if(p!==null)pitches.push(p);}let duration=1;if(source[i]===':'||source[i]==='/'){let op=source[i++],at=i;while(/\d/.test(source[i]||'')&&i<source.length)i++;if(source[i]==='.'&&/\d/.test(source[i+1]||'')){i++;while(/\d/.test(source[i]||'')&&i<source.length)i++;}let raw=source.slice(at,i);if(!/^\d+(\.\d+)?$/.test(raw))fail('时值需要一个数字，例如 :2 或 /2',source,at);let num=Number(raw);duration=op==='/'?1/num:num;if(!Number.isFinite(duration)||duration<.125||duration>16)fail('每个音的时值须在 0.125 到 16 拍之间',source,at);}if(source[i]==='.'){duration*=1.5;i++;}if(duration>16)fail('每个音最多持续 16 拍',source,start);events.push({pitches,beat,duration,index:events.length,start,end:i,token:source.slice(start,i)});beat+=duration;if(events.length>MAX_NOTES||beat>MAX_BEATS)fail('单轨最多 1000 个音、180 拍，请分段制作',source,start);}
return {events,totalBeats:beat};}
function defaultProject(){return {format:'numbered-music-studio',version:1,title:'我的第一首旋律',bpm:110,key:0,volume:.7,loop:false,tracks:[{name:'主旋律',instrument:'piano',volume:.8,mute:false,notation:'1 2 3 5 | 6 5 3:2 | 4 3 2 1 | 2 5 1:2'}],sfx:{preset:'coin',seed:42,frequency:660,endFrequency:1320,duration:.35,attack:.005,decay:.25,noise:0,filter:10000,wave:'square',volume:.6}};}
function cleanProject(p){if(!p||p.format!=='numbered-music-studio'||p.version!==1)throw new Error('这不是支持的 v1 音乐工程文件');function number(v,min,max,name){if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw new Error(name+' 超出范围');return v;}function boolean(v,name){if(typeof v!=='boolean')throw new Error(name+' 必须是开关值');return v;}function str(v,max,name){if(typeof v!=='string'||v.length>max)throw new Error(name+' 不合法');return v;}if(!Array.isArray(p.tracks)||!p.tracks.length||p.tracks.length>4)throw new Error('工程应有 1 到 4 个音轨');let d=defaultProject();let out={format:d.format,version:1,title:str(p.title,100,'标题'),bpm:number(p.bpm,40,240,'速度'),key:number(p.key,0,11,'调性'),volume:number(p.volume,0,1,'主音量'),loop:boolean(p.loop,'循环'),tracks:p.tracks.map(t=>{let cleaned={name:str(t.name,40,'音轨名称'),instrument:str(t.instrument,40,'乐器'),volume:number(t.volume,0,1,'音轨音量'),mute:boolean(t.mute,'静音'),notation:str(t.notation,12000,'乐谱')};if(t.tone!==undefined){let tone=root.StudioTone;if(!tone&&typeof require==='function')tone=require('./track-tone.js');if(!tone)throw Error('音轨音色模块未载入');cleaned.tone=tone.clean(t.tone);}return cleaned;}),sfx:{}};if(!Number.isInteger(out.key))throw new Error('调性必须是整数');let s=p.sfx||d.sfx;for(const [k,min,max]of [['seed',1,999999],['frequency',40,4000],['endFrequency',20,8000],['duration',.05,4],['attack',.001,1],['decay',.01,3],['noise',0,1],['filter',100,20000],['volume',0,1]])out.sfx[k]=number(s[k],min,max,'音效 '+k);out.sfx.wave=['sine','square','sawtooth','triangle'].includes(s.wave)?s.wave:'square';out.sfx.preset=typeof s.preset==='string'?s.preset.slice(0,40):'custom';return out;}
function toMidi(project){let parsed=project.tracks.map(t=>parse(t.notation,t.instrument==='percussion'?0:project.key));let data=[],push=(...x)=>data.push(...x),str=s=>Array.from(s,c=>c.charCodeAt(0)),u32=n=>[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255],vlen=n=>{let a=[n&127];while(n>>=7)a.unshift((n&127)|128);return a;};push(...str('MThd'),0,0,0,6,0,1,0,project.tracks.length+1,1,224);let tempo=Math.round(60000000/project.bpm),conductor=[0,255,81,3,(tempo>>16)&255,(tempo>>8)&255,tempo&255,0,255,47,0];push(...str('MTrk'),...u32(conductor.length),...conductor);let programs={piano:0,guitar:24,bass:33,flute:73,strings:48,brass:56,organ:19,synth:80,drums:118};parsed.forEach((track,ti)=>{let tr=project.tracks[ti],ev=[],ch=tr.instrument==='percussion'?9:ti;for(const e of track.events)if(!tr.mute&&tr.volume>0&&project.volume>0)for(const pitch of e.pitches){const p=ch===9?({0:36,1:36,2:42,3:42,4:38,5:45,6:45,7:46,8:46,9:49,10:49,11:39}[(pitch%12+12)%12]||36):pitch;ev.push({t:Math.round(e.beat*480),bytes:[144+ch,p,Math.max(1,Math.round(tr.volume*project.volume*100))]});ev.push({t:Math.round((e.beat+e.duration*.94)*480),bytes:[128+ch,p,0]});}ev.sort((a,b)=>a.t-b.t||a.bytes[0]-b.bytes[0]);let b=ch===9?[]:[0,192+ch,programs[tr.instrument]||0],prev=0;for(const e of ev){b.push(...vlen(e.t-prev),...e.bytes);prev=e.t;}b.push(...vlen(Math.max(0,Math.round(track.totalBeats*480)-prev)),255,47,0);push(...str('MTrk'),...u32(b.length),...b);});return new Uint8Array(data);}
const api={parse,defaultProject,cleanProject,toMidi,KEYS,MAX_BEATS};if(typeof module!=='undefined')module.exports=api;root.StudioCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
