/* Integrated, local-only score workspace. Original application code. See LICENSE.txt. */
(function(){'use strict';
const C=window.ScoreImportCore,W=window.ScoreWorkspaceCore,A=window.StudioAudio,S=window.StudioApp,T=window.TranscriptionCore,$=id=>document.getElementById(id);if(!C||!W||!A||!S)return;
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;},copy=W.copy;
let score=null,source=null,selectedPart=null,selectedNote=null,page=0,dirty=false,busy=false,history=[],future=[],pending=null,sourceGeneration=0,playGeneration=0,controller=null,ctx=null,voice=null,playBuffer=null,pausedAt=0,startedAt=0,frame=0,playing=false,tempo=1,pdfDoc=null,pdfTask=null,imageObject=null,shownPage=1;
const say=(message,bad=false)=>{$('scStatus').textContent=message;$('scStatus').classList.toggle('bad',bad);};
const current=()=>score&&score.parts.find(p=>p.id===selectedPart),safeName=()=>((score&&score.title)||'乐谱').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,80);
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=node('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function bytesBase64(bytes){let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s);}
function unbase64(s){const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function snapshot(){return {parts:copy(score.parts),title:score.title,totalBeats:score.totalBeats};}
function setBusy(v){busy=v;for(const id of ['scImport','scOpen','scConfigureOmr','scRecognize','scApply','scAdd','scDelete','scPlan','scConfirmHandoff'])$(id).disabled=v;$('scCancelOmr').disabled=!v;}
function resetPending(){pending=null;$('scHandoff').hidden=true;}
function stop(){playGeneration++;if(controller)controller.abort();controller=null;if(voice){voice.onended=null;try{voice.stop();voice.disconnect();}catch{}voice=null;}playing=false;pausedAt=0;playBuffer=null;cancelAnimationFrame(frame);$('scTime').textContent='';$('scPause').disabled=true;$('scPause').textContent='暂停';$('scPlay').disabled=false;$('scWav').disabled=false;}
function mutate(fn){if(!score||busy)return;try{const before=snapshot(),p=copy(score);fn(p);const clean=C.validateScore(p);history.push(before);if(history.length>20)history.shift();future=[];score=clean;stop();dirty=true;resetPending();render();say('修改已保留；请保存乐谱工程备份。');}catch(e){say(e.message,true);render();}}
function undo(redo){if(busy||!score)return;const from=redo?future:history,to=redo?history:future;if(!from.length)return;to.push(snapshot());const snapshotValue=from.pop();score=C.validateScore({...score,...snapshotValue});selectedNote=null;stop();dirty=true;resetPending();render();}
function canReplace(){return !busy&&(!dirty||window.confirm('当前乐谱工程有未保存修改，继续将替换它。数字作曲与音频识别工程不会改变。已保存后继续？'));}
function replaceScore(p,src=null){score=C.validateScore(p);source=src;selectedPart=score.parts[0]?.id;selectedNote=null;page=0;history=[];future=[];dirty=true;tempo=1;stop();resetPending();$('scTempo').value=1;$('scStart').value=0;const end=C.secondsToBeat?C.secondsToBeat(score,Math.min(25,C.beatToSeconds(score,score.totalBeats))):Math.min(score.totalBeats,32);$('scEnd').value=Math.max(.001,Number(end.toFixed(6)));render();}
function selectNote(id){selectedNote=id;const i=current().events.findIndex(e=>e.id===id);if(i>=0)page=Math.floor(i/60);renderNotes();}
function noteLabel(e){if(e.kind==='rest')return '休止 0';if(e.kind==='unpitched')return '无固定音高打击'+(e.midiPitch==null?'（未映射）':' · MIDI '+e.midiPitch);if(!Number.isInteger(e.midiPitch))return 'MIDI '+e.midiPitch+'（微分音）';return ['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'][e.midiPitch%12]+(Math.floor(e.midiPitch/12)-1)+' / '+T.pitchToDigit(e.midiPitch,{tonic:0,mode:'major'})+'（C调）';}
function renderNotes(){const p=current();if(!p)return;$('scPartTitle').textContent=p.name+' · 精确拍数校正';page=Math.max(0,Math.min(page,Math.ceil(p.events.length/60)-1));const chosen=p.events.find(e=>e.id===selectedNote);for(const id of ['scApply','scDelete'])$(id).disabled=!chosen||busy;if(chosen){$('scPitch').value=chosen.midiPitch==null?60:chosen.midiPitch;$('scRest').checked=chosen.kind==='rest';$('scBeat').value=chosen.beat;$('scDuration').value=chosen.duration;$('scVelocity').value=chosen.velocity||100;$('scMeasure').value=chosen.measure==null?'':chosen.measure;$('scVoice').value=chosen.voice||'1';$('scTieStart').checked=!!chosen.tie?.start;$('scTieStop').checked=!!chosen.tie?.stop;$('scSelected').textContent='选中 '+noteLabel(chosen)+'，开始 '+chosen.beat+' 拍 / 时长 '+chosen.duration+' 拍。连音起 / 止须与相邻同音配对，请对照原谱检查。';}else $('scSelected').textContent='选择音符；相同开始拍的音可组成和弦，不会自动量化。';const body=$('scNotes');body.replaceChildren();for(const e of p.events.slice(page*60,(page+1)*60)){const row=node('tr',null,e.id===selectedNote?'selected':''),cell=node('td'),b=node('button','选');b.onclick=()=>selectNote(e.id);cell.append(b);row.append(cell,node('td',(e.measure==null?'—':e.measure)+' / '+(e.voice||1)),node('td',noteLabel(e)),node('td',String(e.beat)),node('td',String(e.duration)),node('td',[e.tie?'连音（待核对）':'',e.chordId?'和弦':'',e.edited?'已校正':''].filter(Boolean).join(' · ')));body.append(row);}$('scPrev').disabled=page===0;$('scNext').disabled=(page+1)*60>=p.events.length;$('scPage').textContent=(page+1)+' / '+Math.max(1,Math.ceil(p.events.length/60))+' 页 · '+p.events.length+' 个事件（含休止）';}
function render(){if(!score){$('scEditor').hidden=true;return;}$('scEditor').hidden=false;$('scTitle').value=score.title||'导入乐谱';$('scSummary').textContent=score.parts.length+' 个声部 · '+score.parts.reduce((n,p)=>n+p.events.length,0)+' 个事件 · '+Number(score.totalBeats.toFixed(3))+' 拍';$('scWarnings').textContent=(score.warnings||[]).join('\n');$('scMaps').textContent='速度：'+score.tempos.map(t=>t.beat+'拍 '+t.bpm+' BPM').join('；')+'\n拍号：'+score.timeSignatures.map(t=>(t.partId?t.partId+' ':'')+t.beat+'拍 '+t.numerator+'/'+t.denominator).join('；')+'\n调号：'+score.keySignatures.map(k=>(k.partId?k.partId+' ':'')+k.beat+'拍 '+k.fifths+'个升/降号 '+k.mode).join('；');$('scUndo').disabled=!history.length||busy;$('scRedo').disabled=!future.length||busy;const selected=new Set(Array.from($('scPartSelection').querySelectorAll('input:checked')).map(n=>n.value));$('scParts').replaceChildren();$('scPartSelection').replaceChildren();for(const p of score.parts){const box=node('div',null,'scorePart'+(p.id===selectedPart?' selected':'')),b=node('button',p.name+' · '+p.events.filter(e=>e.kind==='note').length+' 音');b.onclick=()=>{selectedPart=p.id;selectedNote=null;page=0;render();};box.append(b);const ins=node('select');ins.setAttribute('aria-label',p.name+' 的乐器');for(const i of A.getInstruments().filter(i=>i.id!=='percussion')){const o=node('option',i.name);o.value=i.id;ins.append(o);}if(p.instrument==='percussion'){const o=node('option','原鼓谱（当前不渲染）');o.value='percussion';ins.append(o);}ins.value=p.instrument;ins.disabled=busy;ins.onchange=()=>mutate(s=>{const part=s.parts.find(x=>x.id===p.id);part.instrument=ins.value;part.instrumentOverride=true;});box.append(ins);const vol=node('input');vol.type='range';vol.min=0;vol.max=1;vol.step=.01;vol.value=p.volume;vol.setAttribute('aria-label',p.name+' 音量');vol.disabled=busy;vol.onchange=()=>mutate(s=>{const part=s.parts.find(x=>x.id===p.id);part.volume=Number(vol.value);part.volumeOverride=true;});box.append(vol);for(const [field,text] of [['mute','静音'],['solo','独奏']]){const label=node('label',null,'check'),check=node('input');check.type='checkbox';check.checked=p[field];check.disabled=busy;check.onchange=()=>mutate(s=>{s.parts.find(x=>x.id===p.id)[field]=check.checked;});label.append(check,document.createTextNode(text));box.append(label);}$('scParts').append(box);const label=node('label',null,'check'),check=node('input');check.type='checkbox';check.value=p.id;check.checked=selected.has(p.id);check.onchange=resetPending;label.append(check,document.createTextNode(p.name));$('scPartSelection').append(label);}renderNotes();}
async function readScore(file){if(!file||!canReplace())return;const ext=file.name.toLowerCase().split('.').pop();if(['png','jpg','jpeg','webp','pdf'].includes(ext)){await loadSource(file);return;}setBusy(true);try{const parsed=await C.parseFile(file);sourceGeneration++;await releaseSource();replaceScore(parsed,null);$('scSourcePanel').hidden=true;say('已读取 '+parsed.parts.length+' 个声部。请查看导入警告，选择各声部乐器后演奏。');}catch(e){say('没有替换当前乐谱：'+e.message,true);}finally{setBusy(false);render();}}
async function releaseSource(){if(pdfTask){await pdfTask.destroy();pdfTask=null;}pdfDoc=null;imageObject=null;}
async function loadSource(file){if(file.size>25*1024*1024)throw Error('原谱最多 25 MiB。');const gen=++sourceGeneration,previousSource=source;setBusy(true);try{const ext=file.name.toLowerCase().split('.').pop(),types={pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp'},bytes=new Uint8Array(await file.arrayBuffer()),candidate=W.validateSource({name:file.name,type:types[ext],base64:bytesBase64(bytes),page:1,transform:{}});await prepareSource(candidate,gen);if(gen!==sourceGeneration)return;source=candidate;score=null;selectedPart=null;history=[];future=[];dirty=true;stop();resetPending();render();say('原谱已在本机打开。检查旋转 / 裁切，点击“识别当前页五线谱”。识别会生成待校正草稿。');}catch(e){if(previousSource){try{await prepareSource(previousSource,gen);}catch{}}else{await releaseSource();$('scSourcePanel').hidden=true;}say('原谱打开失败：'+e.message,true);}finally{if(gen===sourceGeneration)setBusy(false);}}
async function prepareSource(src,gen=sourceGeneration){const bytes=unbase64(src.base64);await releaseSource();if(src.type==='application/pdf'){const pdf=await import('./vendor/pdfjs/pdf.min.mjs');pdf.GlobalWorkerOptions.workerSrc='./vendor/pdfjs/pdf.worker.min.mjs';pdfTask=pdf.getDocument({data:bytes,isEvalSupported:false,useSystemFonts:false,disableFontFace:true,maxImageSize:32000000,stopAtErrors:true,standardFontDataUrl:'./vendor/pdfjs/standard_fonts/',cMapUrl:'./vendor/pdfjs/cmaps/',cMapPacked:true,wasmUrl:'./vendor/pdfjs/wasm/'});pdfDoc=await pdfTask.promise;if(pdfDoc.numPages>200)throw Error('PDF 超过 200 页，请先拆分。');$('scPdfPage').max=pdfDoc.numPages;}else{imageObject=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('无法解码这张图片。'));image.src='data:'+src.type+';base64,'+src.base64;});if(imageObject.naturalWidth*imageObject.naturalHeight>32000000)throw Error('图片超过 3200 万像素，请先缩小。');}$('scPdfPage').value=src.page;$('scPdfPage').disabled=!pdfDoc;$('scShowPage').disabled=!pdfDoc;$('scSourceName').textContent=src.name+(pdfDoc?' · 共 '+pdfDoc.numPages+' 页':'');for(const [id,key] of [['scRotation','rotation'],['scCropLeft','left'],['scCropRight','right'],['scCropTop','top'],['scCropBottom','bottom']])$(id).value=src.transform[key];await drawOriginal(src.page,gen);if(gen!==sourceGeneration)return;$('scSourcePanel').hidden=false;drawProcessed(false);}
async function drawOriginal(pageNo,gen=sourceGeneration){const canvas=$('scOriginalCanvas');if(pdfDoc){const p=await pdfDoc.getPage(pageNo);const base=p.getViewport({scale:1}),scale=Math.min(3,4000/Math.max(base.width,base.height)),viewport=p.getViewport({scale});if(viewport.width*viewport.height>32000000)throw Error('PDF 页面过大。');if(gen!==sourceGeneration)return;canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await p.render({canvasContext:canvas.getContext('2d'),viewport}).promise;}else if(imageObject){canvas.width=imageObject.naturalWidth;canvas.height=imageObject.naturalHeight;canvas.getContext('2d').drawImage(imageObject,0,0);}else throw Error('没有原谱页面。');shownPage=pageNo;}
function readTransform(){return W.transform({rotation:Number($('scRotation').value),left:Number($('scCropLeft').value),right:Number($('scCropRight').value),top:Number($('scCropTop').value),bottom:Number($('scCropBottom').value)});}
function drawProcessed(update=true){const tr=readTransform(),a=$('scOriginalCanvas'),b=$('scProcessedCanvas'),sx=a.width*tr.left/100,sy=a.height*tr.top/100,sw=a.width*(1-(tr.left+tr.right)/100),sh=a.height*(1-(tr.top+tr.bottom)/100),r=tr.rotation*Math.PI/180;const w=Math.ceil(Math.abs(sw*Math.cos(r))+Math.abs(sh*Math.sin(r))),h=Math.ceil(Math.abs(sh*Math.cos(r))+Math.abs(sw*Math.sin(r)));if(!w||!h||w*h>32000000)throw Error('校正后图像过大或为空。');b.width=w;b.height=h;const c=b.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,w,h);c.save();c.translate(w/2,h/2);c.rotate(r);c.drawImage(a,sx,sy,sw,sh,-sw/2,-sh/2,sw,sh);c.restore();if(source&&update){source.transform=tr;source.page=shownPage;$('scPdfPage').value=shownPage;}return b;}
async function checkOmr(){try{if(!window.QiyinDesktop?.scoreOmrStatus){$('scOmrStatus').textContent='五线谱图像识别需使用带离线组件的 Windows 客户端；数字乐谱读取不需要它。';return;}const r=await window.QiyinDesktop.scoreOmrStatus();$('scOmrStatus').textContent=r.message||'正在检查本机识谱组件…';$('scConfigureOmr').textContent=r.bundled?'选择其他识谱引擎':'配置五线谱识别';}catch(e){$('scOmrStatus').textContent=e.message;}}
async function recognize(){if(busy||!source)return;if(!window.QiyinDesktop?.scoreOmrRecognize){say('请在带离线组件的 Windows 客户端识别；当前仍可导入 MIDI / MusicXML。',true);return;}if(score&&dirty&&!window.confirm('重新识别会替换当前校正音符。请先保存工程。继续？'))return;setBusy(true);stop();say('正在校验本机识谱组件并识别当前页五线谱；不联网下载。单次识别最多 5 分钟，可取消。');try{const canvas=drawProcessed(),blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('无法生成校正页。');const result=await window.QiyinDesktop.scoreOmrRecognize({name:'score-page-'+source.page+'.png',bytes:await blob.arrayBuffer(),pages:[1]});if(!result.files?.length)throw Error('引擎没有输出可读取的乐谱。');if(result.files.length!==1)throw Error('引擎输出多个乐谱文件，无法确定该用哪份；请用 Audiveris 导出一份合并 MusicXML 再导入。');const f=result.files[0],bytes=new Uint8Array(f.bytes),parsed=await C.parseFile({name:f.name,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),text:async()=>new TextDecoder().decode(bytes)});parsed.warnings.push('这是光学识谱草稿，所有音符均需要对照上方原谱复核。没有可信的自动正确率。',...(result.warnings||[]));const src=source;replaceScore(parsed,src);say('当前页已识别为 '+parsed.parts.length+' 个声部。请先对照原谱校正错音、节拍、休止与连音，再换乐器演奏。');}catch(e){say('识别未完成：'+e.message,true);}finally{setBusy(false);render();checkOmr();}}
function range(){if(!score)throw Error('请先导入乐谱。');const startBeat=Number($('scStart').value),endBeat=Number($('scEnd').value),speed=Number($('scTempo').value);if(!Number.isFinite(speed)||speed<.25||speed>4)throw Error('速度倍率须为 0.25–4。');if(!Number.isFinite(startBeat)||!Number.isFinite(endBeat)||startBeat<0||endBeat<=startBeat||endBeat>score.totalBeats+1e-6)throw Error('请在乐谱范围内选择有效起止拍。');const start=C.beatToSeconds(score,startBeat)/speed,end=C.beatToSeconds(score,endBeat)/speed;if(end-start>90+1e-6)throw Error('试听 / WAV 每次最多 90 秒，请缩短区间。完整乐谱可导出 MIDI。');return {start,end,speed,startBeat,endBeat};}
async function renderAudio(signal){const r=range(),events=C.buildPlaybackEvents(score).map(e=>({...e,start:e.start/r.speed,duration:e.duration/r.speed}));if(events.some(e=>e.instrument==='percussion'&&e.start<r.end&&e.start+e.duration>r.start))throw Error('该区间有原始鼓谱，目前未实现完整 GM 鼓组渲染。请静音鼓部，或明确改成有音高乐器后演奏；鼓谱仍保留在 MIDI。');return A.renderEvents(events,44100,{start:r.start,end:r.end,signal,volume:.8});}
function tick(){if(!playing||!playBuffer)return;const n=Math.min(playBuffer.duration,Math.max(0,ctx.currentTime-startedAt));$('scTime').textContent=n.toFixed(1)+' / '+playBuffer.duration.toFixed(1)+' 秒';frame=requestAnimationFrame(tick);}
function startBuffer(offset){voice=ctx.createBufferSource();voice.buffer=playBuffer;voice.connect(ctx.destination);startedAt=ctx.currentTime-offset;playing=true;voice.onended=()=>{if(playing){playing=false;pausedAt=0;$('scPause').disabled=true;$('scPlay').disabled=false;cancelAnimationFrame(frame);$('scTime').textContent='演奏结束';}};voice.start(0,offset);$('scPause').disabled=false;$('scPause').textContent='暂停';$('scPlay').disabled=true;tick();}
async function play(exporting=false){stop();S.stop();window.TranscriptionUI?.stop();const generation=playGeneration;controller=new AbortController();const signal=controller.signal;try{if(!exporting){ctx=ctx||new (window.AudioContext||window.webkitAudioContext)();await ctx.resume();}$('scPlay').disabled=true;$('scWav').disabled=true;say('正在用所选真实采样 / 合成乐器渲染…');const audio=await renderAudio(signal);if(generation!==playGeneration||signal.aborted)return;if(exporting){download(A.encodeWav(audio.samples,audio.sampleRate),safeName()+'-乐谱演奏.wav','audio/wav');say('已导出所选片段 WAV，包含当前乐器声音。发布作品时请保留素材署名要求。');}else{playBuffer=ctx.createBuffer(1,audio.samples.length,audio.sampleRate);playBuffer.copyToChannel(audio.samples,0);startBuffer(0);say('正在演奏，可暂停 / 继续。');}}catch(e){if(generation===playGeneration&&!signal.aborted)say(e.message,true);}finally{if(generation===playGeneration){controller=null;$('scWav').disabled=false;if(!playing)$('scPlay').disabled=false;}}}
function pause(){if(!playBuffer||!ctx)return;if(playing){pausedAt=Math.min(playBuffer.duration,ctx.currentTime-startedAt);voice.onended=null;voice.stop();voice.disconnect();voice=null;playing=false;cancelAnimationFrame(frame);$('scPause').textContent='继续';}else if(pausedAt<playBuffer.duration)startBuffer(pausedAt);}
function save(){if(!score){say('先导入数字乐谱或完成识别，再保存工程。',true);return;}try{const p=W.pack(score,source,Number($('scTempo').value));download(JSON.stringify(p),safeName()+'.七音乐谱.json','application/json');say('已生成乐谱工程文件，包含原始导入数据、原谱图片 / PDF、当前校正音符和乐器设置。请完成保存对话框。');}catch(e){say(e.message,true);}}
async function open(file){if(!file||!canReplace())return;if(file.size>64*1024*1024){say('工程超过 64 MiB。',true);return;}setBusy(true);try{const p=W.parseProject(await file.text()),gen=++sourceGeneration;if(p.source)await prepareSource(p.source,gen);else{await releaseSource();$('scSourcePanel').hidden=true;}replaceScore(p.score,p.source);tempo=p.tempo;$('scTempo').value=tempo;dirty=false;say('乐谱工程已恢复，原始导入数据与手工校正均已保留。');}catch(e){if(source){try{await prepareSource(source,sourceGeneration);}catch{}}say('打开失败：'+e.message,true);}finally{setBusy(false);render();}}
$('scImport').onclick=()=>{$('scFile').value='';$('scFile').click();};$('scFile').onchange=e=>readScore(e.target.files[0]).catch(err=>say(err.message,true));$('scOpen').onclick=()=>{$('scProjectFile').value='';$('scProjectFile').click();};$('scProjectFile').onchange=e=>open(e.target.files[0]);$('scSave').onclick=save;
$('scConfigureOmr').onclick=async()=>{try{if(!window.QiyinDesktop?.scoreOmrConfigure)throw Error('请在 Windows 客户端使用此功能。独立 Audiveris 官方下载：https://github.com/Audiveris/audiveris/releases');await window.QiyinDesktop.scoreOmrConfigure();await checkOmr();}catch(e){say(e.message,true);}};
$('scRecognize').onclick=recognize;$('scCancelOmr').onclick=async()=>{if(window.QiyinDesktop?.scoreOmrCancel){await window.QiyinDesktop.scoreOmrCancel();say('已请求取消，正在等待本机引擎退出。');}};
$('scPreviewTransform').onclick=()=>{if(busy)return;try{drawProcessed();dirty=true;say('已预览校正后的页面，原始文件未改变。');}catch(e){say(e.message,true);}};$('scShowPage').onclick=async()=>{if(busy||!pdfDoc)return;try{const p=Number($('scPdfPage').value);if(!Number.isInteger(p)||p<1||p>pdfDoc.numPages)throw Error('PDF 页码超出范围。');await drawOriginal(p);drawProcessed();dirty=true;say('显示 PDF 第 '+p+' 页。识别只处理这一页。');}catch(e){say(e.message,true);}};
$('scTitle').onchange=()=>mutate(p=>{p.title=$('scTitle').value;});$('scUndo').onclick=()=>undo(false);$('scRedo').onclick=()=>undo(true);$('scPrev').onclick=()=>{page--;renderNotes();};$('scNext').onclick=()=>{page++;renderNotes();};
function editedNote(old){if(!Number.isInteger(Number($('scPitch').value))||Number($('scDuration').value)<=0)throw Error('手工校正需要整数 MIDI 音高和大于 0 的时长。');const rest=$('scRest').checked,n={...(old||{}),kind:rest?'rest':'note',beat:Number($('scBeat').value),duration:Number($('scDuration').value),midiPitch:rest?null:Number($('scPitch').value),velocity:Number($('scVelocity').value),measure:$('scMeasure').value||null,voice:$('scVoice').value||'1',edited:true};if(old&&!old.original)n.original=copy(old);delete n.tie;if(!rest&&($('scTieStart').checked||$('scTieStop').checked))n.tie={start:$('scTieStart').checked,stop:$('scTieStop').checked};delete n.pitch;return n;}
$('scApply').onclick=()=>mutate(p=>{const part=p.parts.find(x=>x.id===selectedPart),i=part.events.findIndex(e=>e.id===selectedNote);if(i<0)throw Error('先选择音符。');part.events[i]=editedNote(part.events[i]);});$('scAdd').onclick=()=>mutate(p=>{const part=p.parts.find(x=>x.id===selectedPart),e=editedNote();e.id=part.id+'-manual-'+Date.now().toString(36)+'-'+part.events.length;e.partId=part.id;e.staff=1;part.events.push(e);selectedNote=e.id;p.totalBeats=Math.max(p.totalBeats,e.beat+e.duration);});$('scDelete').onclick=()=>mutate(p=>{const part=p.parts.find(x=>x.id===selectedPart);part.events=part.events.filter(e=>e.id!==selectedNote);selectedNote=null;});
for(const id of ['scStart','scEnd','scTempo'])$(id).onchange=()=>{stop();resetPending();if(id==='scTempo'){tempo=Number($('scTempo').value);dirty=true;}};$('scPlay').onclick=()=>play(false);$('scWav').onclick=()=>play(true);$('scPause').onclick=pause;$('scStop').onclick=stop;
$('scMidi').onclick=()=>{try{const p=copy(score),speed=Number($('scTempo').value);W.pack(p,null,speed);p.tempos=p.tempos.map(t=>({...t,bpm:t.bpm*speed}));const midi=C.toMidi(p);download(midi,safeName()+'.mid','audio/midi');say('完整 MIDI 已生成，包含当前可听声部与速度。需当前采样声音请导出 WAV。'+(midi.warnings||[]).join(' '));}catch(e){say(e.message,true);}};
$('scPlan').onclick=()=>{try{const r=range(),ids=Array.from($('scPartSelection').querySelectorAll('input:checked')).map(n=>n.value);pending=W.toComposer(score,ids,{start:r.startBeat,end:r.endBeat,tempo:r.speed});$('scHandoffText').textContent=pending.summary;$('scHandoff').hidden=false;say('仅生成转换预览，确认后才替换数字作曲工程。');}catch(e){resetPending();say(e.message,true);}};$('scCancelHandoff').onclick=resetPending;$('scConfirmHandoff').onclick=()=>{if(!pending||busy)return;try{S.importProject(pending.project);resetPending();S.showWorkspace('music');$('notice').textContent='已导入所选乐谱片段；完整多声部原谱与校正保留在“乐谱导入”。';}catch(e){say(e.message,true);}};
window.addEventListener('studio:workspace',e=>{stop();resetPending();if(e.detail.tab==='score')$('notice').textContent='乐谱工程、数字作曲与音频识别分别保存。导入不会自动覆盖其他工作区。';});window.addEventListener('beforeunload',e=>{stop();if(dirty||busy){e.preventDefault();e.returnValue='';}});document.addEventListener('keydown',e=>{if($('scorePanel').hidden||!(e.ctrlKey||e.metaKey))return;if(e.key.toLowerCase()==='s'){e.preventDefault();save();}else if(!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();undo(e.shiftKey||e.key.toLowerCase()==='y');}});
window.ScoreUI={getScore:()=>score?copy(score):null,getState:()=>({dirty,busy,selectedPart,selectedNote,playing,pausedAt}),importScore:replaceScore,readScore,open,selectNote,renderAudio,play,pause,stop,save};checkOmr();
})();
