/* Local-only transcription workspace. No remote inference, uploads or audio in JSON. */
(function () {
'use strict';
const T=window.TranscriptionCore,A=window.StudioAudio,S=window.StudioApp,$=id=>document.getElementById(id),copy=x=>JSON.parse(JSON.stringify(x));
if(!T||!A||!S)return;
const labels={vocals:'人声',drums:'鼓组',bass:'贝斯',other:'其他伴奏'},cueNames={coin:'金币',jump:'跳跃',laser:'激光',explosion:'爆炸',hit:'打击',whoosh:'挥动',custom:'自定义'},fileIds={vocals:'trFileVocals',bass:'trFileBass',drums:'trFileDrums',other:'trFileOther'},PAGE_SIZE=60;
let project=null,selectedStem='vocals',selectedNote=null,page=0,history=[],future=[],dirty=false,ready=false,busy=false,jobId=null,cancelRequested=false,pendingFiles=[],pendingResults=[],requestIndex=0;
let refs=new Map(),decoded=new Map(),objectUrls=[],context=null,sources=[],playToken=0,playFrame=0,renderController=null,pendingHandoff=null,canvasHits=[],resumeContext=null,serial=0,audioGeneration=0;
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const status=(message,bad=false)=>{$('trStatus').textContent=message;$('trStatus').classList.toggle('bad',bad);};
const current=()=>project&&project.stems.find(s=>s.id===selectedStem);
const safeName=()=>((project&&project.title)||'音频识别工程').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,80);
const uid=prefix=>prefix+'-manual-'+Date.now().toString(36)+'-'+(++serial);
const localOrigin=()=>/^https?:$/.test(location.protocol)&&['localhost','127.0.0.1','[::1]'].includes(location.hostname);
const audible=s=>!s.mute&&s.volume>0&&(!project.stems.some(x=>x.solo)||s.solo);
const sourceOffset=()=>project?project.source.offset:0;
const keepServiceOpen=()=>window.QiyinDesktop?'请保持七音客户端打开。':'请保持本地启动窗口打开。';
function clearAudio(){audioGeneration++;stop();for(const url of objectUrls)URL.revokeObjectURL(url);objectUrls=[];refs.clear();decoded.clear();}
function download(data,name,type){const blob=data instanceof Blob?data:new Blob([data],{type});const url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function range(){if(!project)throw Error('请先识别音频或打开识别工程。');const start=Number($('trPreviewStart').value),end=Number($('trPreviewEnd').value);if(!Number.isFinite(start)||!Number.isFinite(end)||start<project.source.offset||end>project.duration+1e-6||end<=start)throw Error('试听区间须位于 '+project.source.offset.toFixed(3)+'–'+project.duration.toFixed(3)+' 秒内，且结束晚于开始。');if(end-start>90+1e-6)throw Error('重编试听 / WAV 每次最多 90 秒。请缩短试听区间；完整音符仍可保存为 JSON 或 MIDI。');return {start,end};}
function mutate(fn){if(!project||busy)return;try{const p=copy(project);fn(p);const clean=T.validateProject(p);stop();history.push(copy(project));if(history.length>40)history.shift();future=[];project=clean;dirty=true;pendingHandoff=null;$('trHandoff').hidden=true;render();status('修改已保留在当前识别工程中。请点“保存识别工程”下载备份。');}catch(e){status(e.message,true);render();}}
function undo(redo){const from=redo?future:history,to=redo?history:future;if(!from.length||busy)return;stop();to.push(copy(project));project=from.pop();selectedNote=null;dirty=true;pendingHandoff=null;$('trHandoff').hidden=true;render();}
function replaceProject(p,audioRefs){const clean=T.validateProject(p);clearAudio();project=clean;refs=audioRefs||new Map();selectedStem=project.stems.find(s=>s.events.length)?.id||'drums';selectedNote=null;page=0;history=[];future=[];dirty=false;pendingHandoff=null;$('trHandoff').hidden=true;$('trPreviewStart').value=project.source.offset;$('trPreviewEnd').value=Math.min(project.duration,project.source.offset+25);$('trSfxOnset').value=project.source.offset;render();}
function confirmReplace(){return !project||!dirty||window.confirm('当前识别工程有未保存修改。继续会替换识别工程；数字作曲工程不会改变。已保存备份后继续？');}
function render(){if(!project)return;$('trEditor').hidden=false;$('trEmptyProject').hidden=true;$('trTitle').value=project.title;$('trUndo').disabled=!history.length||busy;$('trRedo').disabled=!future.length||busy;$('trBpm').value=project.overrides.bpm==null?'':project.overrides.bpm;$('trKey').value=project.overrides.key?project.overrides.key.tonic+':'+project.overrides.key.mode:'';const total=project.stems.reduce((n,s)=>n+s.events.length,0),key=T.effectiveKey(project),keyName=StudioCore.KEYS[key.tonic]+(key.mode==='minor'?' 小调':' 大调');$('trSummary').textContent=project.source.name+' · '+project.source.offset.toFixed(2)+'–'+project.duration.toFixed(2)+' 秒 · '+total+' 个可编辑音符';$('trAnalysis').textContent=(project.overrides.bpm!=null?'手动速度 ':project.analysis.bpm?'估计速度 ':'未估计速度，暂用 ')+T.effectiveBpm(project)+' BPM · '+(project.overrides.key?'手动调性 ':project.analysis.key?'估计调性 ':'未估计调性，暂用 ')+keyName+'（估计需听辨）';$('trStems').replaceChildren();for(const stem of project.stems){const b=node('button',null,'trStemCard'+(stem.id===selectedStem?' active':''));b.dataset.stem=stem.id;b.setAttribute('aria-pressed',stem.id===selectedStem?'true':'false');b.append(node('strong',labels[stem.id]),node('small',(stem.id==='drums'?'原始打击声音频':stem.events.length+' 个音符')+' · '+(refs.has(stem.id)?'原音已连接':'未连接原音')+(stem.mute?' · 静音':'')+(stem.solo?' · 独奏':'')));b.onclick=()=>{stop();selectedStem=stem.id;selectedNote=null;page=0;render();};$('trStems').append(b);}const stem=current();$('trStemHeading').textContent=labels[stem.id]+(stem.id==='drums'?' · 原始波形':' · 音符校正');$('trNoteCount').textContent=stem.id==='drums'?'不生成伪音高':stem.events.length+' 个音符，全部保留';$('trInstrument').value=stem.instrument;$('trInstrument').disabled=stem.id==='drums';$('trVolume').value=stem.volume;$('trMute').checked=stem.mute;$('trSolo').checked=stem.solo;$('trPitchedEditor').hidden=stem.id==='drums';$('trDrumNotice').hidden=stem.id!=='drums';$('trDownloadStem').disabled=!refs.has(stem.id);$('trPlayStem').disabled=!refs.has(stem.id);$('trPlayOriginal').disabled=!refs.has('original');renderNotes();renderCues();drawTimeline();}
function noteName(n){return ['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'][n%12]+(Math.floor(n/12)-1);}
function selectNote(id){selectedNote=id;const index=current().events.findIndex(e=>e.id===id);if(index>=0)page=Math.floor(index/PAGE_SIZE);renderNotes();drawTimeline();}
function renderNotes(){const stem=current();if(!stem)return;const events=stem.events;page=Math.max(0,Math.min(page,Math.ceil(events.length/PAGE_SIZE)-1));const chosen=events.find(e=>e.id===selectedNote);if(!chosen)selectedNote=null;for(const id of ['trApplyNote','trDeleteNote'])$(id).disabled=!chosen;if(chosen){$('trPitch').value=chosen.midiPitch;$('trOnset').value=chosen.onset.toFixed(6);$('trEnd').value=chosen.end.toFixed(6);$('trVelocity').value=chosen.velocity;$('trSelectedNote').textContent='已选 '+T.pitchToDigit(chosen.midiPitch,T.effectiveKey(project))+' / '+noteName(chosen.midiPitch)+'；原始识别 '+chosen.original.onset.toFixed(3)+'–'+chosen.original.end.toFixed(3)+' 秒。修改不会量化其他音符。';}else{$('trSelectedNote').textContent='点击列表或时间线选择音符。可精确编辑秒数；音高用 MIDI 数字，60=C4。';}const body=$('trNoteRows');body.replaceChildren();events.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE).forEach((e,index)=>{const row=node('tr',null,e.id===selectedNote?'selected':'');const c=node('td'),b=node('button','选 '+(page*PAGE_SIZE+index+1));b.dataset.note=e.id;b.onclick=()=>selectNote(e.id);c.append(b);row.append(c,node('td',T.pitchToDigit(e.midiPitch,T.effectiveKey(project))+' / '+noteName(e.midiPitch)),node('td',e.onset.toFixed(3)+' → '+e.end.toFixed(3)),node('td',String(e.velocity)),node('td',e.modelScore==null?'人工 / 未提供':e.modelScore.toFixed(3)+'（待听辨）'));body.append(row);});if(!events.length){const row=node('tr'),cell=node('td','这一轨没有识别到音符。可试听原音，然后手动添加；不会凭空补出旋律。');cell.colSpan=5;row.append(cell);body.append(row);}$('trPrevPage').disabled=page===0;$('trNextPage').disabled=(page+1)*PAGE_SIZE>=events.length;$('trPageLabel').textContent=events.length?'第 '+(page+1)+' / '+Math.ceil(events.length/PAGE_SIZE)+' 页 · 全部 '+events.length+' 个音符':'暂无音符';}
function renderCues(){$('trSfxList').replaceChildren();for(const c of project.sfxEvents){const div=node('div',c.onset.toFixed(2)+' 秒 · '+(cueNames[c.params.preset]||'自定义'),'trCue'),b=node('button','删除');b.onclick=()=>mutate(p=>{p.sfxEvents=p.sfxEvents.filter(x=>x.id!==c.id);});div.append(b);$('trSfxList').append(div);}}
function drawTimeline(){const canvas=$('trTimeline'),ctx=canvas.getContext('2d');if(!ctx||!project)return;let r;try{r=range();}catch(e){$('trTimelineEmpty').textContent=e.message;return;}const w=canvas.width,h=canvas.height,left=45,top=22,bottom=h-28;ctx.clearRect(0,0,w,h);ctx.fillStyle='#f4f7ef';ctx.fillRect(0,0,w,h);ctx.font='11px system-ui';canvasHits=[];for(let i=0;i<=5;i++){const x=left+(w-left-15)*i/5;ctx.strokeStyle='#dce5d5';ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke();ctx.fillStyle='#74866c';ctx.fillText((r.start+(r.end-r.start)*i/5).toFixed(1)+'s',x-12,h-9);}const stem=current();$('trTimelineEmpty').textContent='';if(stem.id==='drums'){const buffer=decoded.get('drums');if(!buffer){$('trTimelineEmpty').textContent=refs.has('drums')?'点“当前轨原声”载入真实波形。':'鼓组音频未连接。打开 JSON 后请重连对应分轨 WAV。';return;}const samples=buffer.getChannelData(0),rate=buffer.sampleRate,offset=refs.get('drums').offset;ctx.strokeStyle='#9b6c40';ctx.beginPath();for(let x=left;x<w-15;x++){const a=Math.max(0,Math.floor((r.start-offset+(x-left)/(w-left-15)*(r.end-r.start))*rate)),b=Math.min(samples.length,Math.ceil((r.start-offset+(x-left+1)/(w-left-15)*(r.end-r.start))*rate));let low=0,high=0;for(let n=a;n<b;n++){low=Math.min(low,samples[n]);high=Math.max(high,samples[n]);}ctx.moveTo(x,(top+bottom)/2+low*75);ctx.lineTo(x,(top+bottom)/2+high*75);}ctx.stroke();return;}const notes=stem.events.filter(e=>e.end>r.start&&e.onset<r.end);if(!notes.length){$('trTimelineEmpty').textContent='当前试听区间没有音符。换一个区间，或手动添加音符。';return;}const low=Math.max(0,Math.min(...notes.map(e=>e.midiPitch))-2),high=Math.min(127,Math.max(...notes.map(e=>e.midiPitch))+2),unit=(bottom-top)/(high-low+1);for(let n=low;n<=high;n++){if(n%12!==0)continue;const y=bottom-(n-low+.5)*unit;ctx.fillStyle='#73866b';ctx.fillText(noteName(n),5,y+3);ctx.strokeStyle='#e0e8d9';ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(w-15,y);ctx.stroke();}for(const e of notes){const x=left+(Math.max(r.start,e.onset)-r.start)/(r.end-r.start)*(w-left-15),width=Math.max(3,(Math.min(r.end,e.end)-Math.max(r.start,e.onset))/(r.end-r.start)*(w-left-15)),y=bottom-(e.midiPitch-low+1)*unit,height=Math.max(4,Math.min(18,unit-1));ctx.fillStyle=e.id===selectedNote?'#db9348':'#4c8b6a';ctx.fillRect(x,y,width,height);canvasHits.push({id:e.id,x,y,width,height});}}
$('trTimeline').onclick=e=>{const c=$('trTimeline'),r=c.getBoundingClientRect();if(!r.width)return;const x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height;const hit=canvasHits.findLast?canvasHits.findLast(a=>x>=a.x&&x<=a.x+a.width&&y>=a.y-3&&y<=a.y+a.height+3):canvasHits.slice().reverse().find(a=>x>=a.x&&x<=a.x+a.width&&y>=a.y-3&&y<=a.y+a.height+3);if(hit)selectNote(hit.id);};
function audioContext(){if(!context){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('浏览器不支持音频播放，请使用新版 Edge / Chrome。');context=new AC();}return context;}
function stop(){playToken++;if(renderController)renderController.abort();renderController=null;for(const s of sources){try{s.stop();s.disconnect();}catch(e){}}sources=[];cancelAnimationFrame(playFrame);$('trPlaybackTime').textContent='';$('trPlayNotes').disabled=false;$('trExportWav').disabled=false;}
async function loadAudio(id){if(decoded.has(id))return decoded.get(id);const generation=audioGeneration,ref=refs.get(id);if(!ref)throw Error('没有连接'+(id==='original'?'原始片段':labels[id])+'音频。请重连对应 WAV。');const response=await fetch(ref.url);if(!response.ok)throw Error('该分轨音频已失效（本地服务重启或保留任务已满）。请重连之前保存的 WAV，或重新识别。');const buffer=await audioContext().decodeAudioData(await response.arrayBuffer());if(generation!==audioGeneration||refs.get(id)!==ref)throw Object.assign(Error('音频来源已变化，忽略旧音频。'),{name:'AbortError'});decoded.set(id,buffer);drawTimeline();return buffer;}
function playBuffer(buffer,start,duration,token,label){if(token!==playToken)return;const ctx=audioContext(),s=ctx.createBufferSource();s.buffer=buffer;s.connect(ctx.destination);sources.push(s);s.start(0,start,duration);const started=ctx.currentTime;function tick(){if(token!==playToken)return;$('trPlaybackTime').textContent=label+' '+Math.min(duration,ctx.currentTime-started).toFixed(1)+' / '+duration.toFixed(1)+' 秒';playFrame=requestAnimationFrame(tick);}tick();s.onended=()=>{if(token===playToken){cancelAnimationFrame(playFrame);$('trPlaybackTime').textContent='试听结束';sources=sources.filter(x=>x!==s);}};}
async function playRaw(id){stop();S.stop();const token=playToken;try{const r=range(),ctx=audioContext();await ctx.resume();const b=await loadAudio(id);if(token!==playToken)return;const from=r.start-refs.get(id).offset;if(from<0||from+r.end-r.start>b.duration+.05)throw Error('连接的音频长度或起点不匹配此工程。请重连与分析片段一致的 WAV。');playBuffer(b,from,r.end-r.start,token,id==='original'?'A 原音':'分轨原音');status('正在播放原始音频，不是识别后的合成音。');}catch(e){if(token===playToken)status(e.message,true);}}
async function renderEdited(signal){const r=range();if(!A.renderEvents)throw Error('精确时间音频引擎未载入，请保留完整文件夹。');const result=await A.renderEvents(T.buildPlaybackEvents(project),44100,{...r,sfxEvents:project.sfxEvents,signal});const drum=project.stems.find(s=>s.id==='drums');if($('trKeepDrums').checked&&audible(drum)){if(refs.has('drums')){const b=await loadAudio('drums');if(signal.aborted)throw Error('已取消渲染');const origin=refs.get('drums').offset;if(r.start-origin<0||r.end-origin>b.duration+.05)throw Error('鼓组音频长度 / 起点不匹配，请重连原始分轨 WAV。');const channels=Array.from({length:b.numberOfChannels},(_,i)=>b.getChannelData(i));for(let i=0;i<Math.min(result.samples.length,Math.ceil((r.end-r.start)*result.sampleRate));i++){const n=(r.start-origin+i/result.sampleRate)*b.sampleRate,a=Math.floor(n),f=n-a;if(a<0||a>=b.length)continue;let value=0;for(const ch of channels)value+=((ch[a]||0)*(1-f)+(ch[a+1]||0)*f)/channels.length;result.samples[i]=Math.max(-1,Math.min(1,result.samples[i]+value*drum.volume));}}else{status('鼓组原音未连接，本次重编只有音符与音效。需要鼓组时请先重连分轨 WAV。',true);throw Error('已开启保留鼓组，但鼓轨原音未连接。请重连鼓组 WAV，或取消“保留鼓组原音”后继续。');}}return result;}
async function playNotes(exporting){stop();S.stop();const token=playToken;renderController=new AbortController();const controller=renderController;try{const ctx=exporting?null:audioContext();if(ctx)await ctx.resume();$('trPlayNotes').disabled=true;$('trExportWav').disabled=true;status('正在按原始秒数渲染重编音频…');const result=await renderEdited(controller.signal);if(token!==playToken||controller.signal.aborted)return;if(exporting){const r=range();download(A.encodeWav(result.samples,result.sampleRate),safeName()+'-'+r.start.toFixed(2)+'至'+r.end.toFixed(2)+'秒-重编.wav','audio/wav');status('已生成当前试听区间的重编 WAV（含可听音轨与音效）。采样音色发布时请保留“素材署名.txt”。');}else{const b=ctx.createBuffer(1,result.samples.length,result.sampleRate);b.copyToChannel(result.samples,0);playBuffer(b,0,b.duration,token,'B 重编');status('正在播放修改后的音符与音效。识别可能错音，请与 A 原始片段逐段比较。');}}catch(e){if(token===playToken&&!controller.signal.aborted)status(e.message,true);}finally{if(token===playToken){$('trPlayNotes').disabled=false;$('trExportWav').disabled=false;renderController=null;}}}
function apiAudio(url){if(typeof url!=='string'||!/^\/api\/jobs\/[A-Za-z0-9_-]+\/audio\/(original|vocals|bass|drums|other)$/.test(url))throw Error('本地服务返回了非预期音频地址，已拒绝连接。');return url;}
async function jsonRequest(path,options){const response=await fetch(path,options);let data;try{data=await response.json();}catch(e){throw Error('本地服务没有返回有效 JSON。请检查启动窗口。');}if(!response.ok)throw Error(typeof data.error==='string'?data.error:'本地服务返回错误 '+response.status);return data;}
async function checkService(){if(!localOrigin()){ready=false;$('trServiceTitle').textContent='第一次使用：先启动本地音频识别';$('trServiceText').textContent=window.QiyinDesktop?'请在窗口顶部点“准备音频识别”。首次需下载本地组件与模型，完成后在此导入音频；音频不会上传云端。':'请先解压整个文件夹，再双击“启动七音-含音频识别.cmd”（Windows）。首次下载约 1–2 GB 依赖与模型，建议 6 GB 空间 / 8 GB 内存；完成后会打开 http://127.0.0.1:8765。直接双击 index.html 仍可离线作曲，但不能运行音频识别。音频不会上传到云端。其他系统请看本地安装说明。';$('trStart').disabled=true;return;}try{const h=await jsonRequest('/api/health');ready=!!h.ready;$('trService').classList.toggle('ready',ready);$('trServiceTitle').textContent=ready?'本地识别服务已就绪':'本地服务已连接，模型尚未就绪';$('trServiceText').textContent=ready?'在本机处理音频，不上传到云端。模型估计分轨与音符，完成后仍需听辨校正。首次加载模型可能较慢。':((window.QiyinDesktop?'请在窗口顶部点“准备音频识别”，安装完成后再检查。缺少：':'请保持启动窗口打开，等待安装完成后再检查。缺少：')+(h.missing||[]).join('、'));$('trStart').disabled=!ready||busy;}catch(e){ready=false;$('trService').classList.remove('ready');$('trServiceTitle').textContent='尚未连接本地识别服务';$('trServiceText').textContent=(window.QiyinDesktop?'请在窗口顶部点“准备音频识别”。首次安装完成后会连接本机服务。当前连接错误：':'请运行“启动七音-含音频识别.cmd”，并在自动打开的 http://127.0.0.1:8765 页面继续。不要关闭启动窗口。连接错误：')+e.message;$('trStart').disabled=true;}}
function setBusy(value){busy=value;for(const n of document.querySelectorAll('#trEditor input,#trEditor select,#trEditor button'))n.disabled=value; if(!value&&project)render();$('trStart').disabled=!ready||busy;$('trCancel').hidden=!busy;$('trCancel').disabled=false;for(const id of ['trInputMode','trRangeMode','trOffset','trAudioFile',...Object.values(fileIds),'trOpen','trOpenEmpty'])$(id).disabled=busy;$('trProgressWrap').hidden=!busy;$('trResume').hidden=true;}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function pollJob(id){while(true){const job=await jsonRequest('/api/jobs/'+encodeURIComponent(id));$('trProgress').value=typeof job.progress==='number'?Math.max(0,Math.min(1,job.progress)):0;$('trProgressLabel').textContent=(pendingFiles.length>1?'第 '+(requestIndex+1)+' / '+pendingFiles.length+' 轨 · ':'')+(job.stage||job.status)+' · '+Math.round(($('trProgress').value||0)*100)+'%';if(job.status==='done')return await jsonRequest('/api/jobs/'+encodeURIComponent(id)+'/result');if(job.status==='error')throw Error(job.error||'识别失败，请检查启动窗口。');if(job.status==='cancelled')throw Object.assign(Error('任务已取消；已有识别工程与简谱未改变。'),{cancelled:true});if(!['queued','running'].includes(job.status))throw Error('未知任务状态：'+job.status);await sleep(1100);}}
function selectedFiles(){const mode=$('trInputMode').value;if(mode==='mix'){const f=$('trAudioFile').files[0];if(!f)throw Error('请先选择 MP3 / WAV 音频。');return [{file:f,stem:null}];}const out=[];for(const [stem,id]of Object.entries(fileIds)){const f=$(id).files[0];if(f)out.push({file:f,stem});}if(!out.length)throw Error('请至少选择一个分轨文件。');return out;}
function mergeResults(results){if(!results.length)throw Error('任务没有返回结果。');let p=T.fromBackendResult(results[0],{name:results[0].sourceName,title:results.length>1?'我的分轨识别工程':results[0].sourceName});const audio=new Map();for(let i=0;i<results.length;i++){const result=results[i],q=T.fromBackendResult(result);if(Math.abs(q.source.offset-p.source.offset)>1e-6||Math.abs(q.duration-p.duration)>.05)throw Error('所选分轨的片段长度不一致，无法可靠对齐。请使用同一起点、同样长度的分轨；旧工程未改变。');if(results.length>1){p.source.duration=Math.max(p.source.duration,q.source.duration);p.duration=Math.max(p.duration,q.duration);p.source.clipDuration=p.duration-p.source.offset;}for(const stem of result.stems){p.stems[p.stems.findIndex(s=>s.id===stem.id)]=q.stems.find(s=>s.id===stem.id);if(stem.audioUrl)audio.set(stem.id,{url:apiAudio(stem.audioUrl),offset:result.offset});}if(results.length===1&&result.mode!=='stem'&&result.originalAudioUrl)audio.set('original',{url:apiAudio(result.originalAudioUrl),offset:result.offset});}if(results.length>1){p.analysis={bpm:null,key:null};p.source.name='已分轨音频（'+results.length+' 轨）';}replaceProject(T.validateProject(p),audio);dirty=true;if(!audio.has('drums'))$('trKeepDrums').checked=false;else $('trKeepDrums').checked=true;return results.flatMap(r=>r.warnings||[]);}
async function continueJobs(resume){try{for(;requestIndex<pendingFiles.length;requestIndex++){if(cancelRequested&&!jobId)throw Object.assign(Error('任务已取消；已有工程未改变。'),{cancelled:true});const item=pendingFiles[requestIndex];if(!resume){const params=new URLSearchParams({mode:item.stem?'stem':resumeContext.mode,offset:String(resumeContext.offset)});if(item.stem){params.set('stem',item.stem);params.set('full',resumeContext.mode==='full'?'1':'0');}status('正在将 '+item.file.name+' 交给本机识别服务。音频不会发送到互联网。');const job=await jsonRequest('/api/jobs?'+params,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':encodeURIComponent(item.file.name)},body:item.file});if(!job.id||!/^[A-Za-z0-9_-]+$/.test(job.id))throw Error('本地服务未返回有效任务编号。');jobId=job.id;if(cancelRequested)await jsonRequest('/api/jobs/'+jobId+'/cancel',{method:'POST'});}resume=false;status('正在处理 '+item.file.name+'。'+keepServiceOpen());const result=await pollJob(jobId);if(cancelRequested)throw Object.assign(Error('任务已取消；已有工程未改变。'),{cancelled:true});pendingResults.push(result);jobId=null;}const warnings=mergeResults(pendingResults);status('识别完成。先选一轨，用 A / B 试听，再校正错音。没有自动量化或覆盖数字作曲工程。'+(warnings.length?'\n'+warnings.join('\n'):''));setBusy(false);resumeContext=null;}catch(e){if(e.cancelled){jobId=null;resumeContext=null;setBusy(false);status(e.message);}else if(jobId&&e instanceof TypeError){$('trResume').hidden=false;$('trCancel').hidden=false;status('连接中断，任务状态尚未确认。当前工程没有改变。'+keepServiceOpen()+'点“重新连接当前任务”；不要重复开始。'+e.message,true);}else{jobId=null;resumeContext=null;setBusy(false);status(e.message+'\n已有识别工程与数字作曲工程没有改变。',true);}}}
async function startJob(){if(busy)return;try{if(!ready)throw Error('请先连接本地识别服务。');const files=selectedFiles(),offset=Number($('trOffset').value);if(!Number.isFinite(offset)||offset<0||offset>86400)throw Error('起点需为有效的非负秒数。');for(const {file}of files){if(!/\.(mp3|wav)$/i.test(file.name))throw Error('请选择 MP3 或 WAV 文件：'+file.name);if(file.size>104857600)throw Error(file.name+' 超过 100 MB 上限。');if(!file.size)throw Error(file.name+' 是空文件。');}if(!confirmReplace())return;stop();pendingFiles=files;pendingResults=[];requestIndex=0;jobId=null;cancelRequested=false;resumeContext={mode:$('trRangeMode').value,offset};setBusy(true);$('trProgress').value=0;$('trProgressLabel').textContent='准备本地任务';await continueJobs(false);}catch(e){status(e.message,true);}}
async function cancelJob(){if(!busy)return;cancelRequested=true;$('trCancel').disabled=true;status('正在请求停止本地任务，请等待服务确认。');if(jobId){try{await jsonRequest('/api/jobs/'+jobId+'/cancel',{method:'POST'});if(!$('trResume').hidden){$('trResume').hidden=true;await continueJobs(true);}}catch(e){$('trCancel').disabled=false;status('取消尚未确认：'+e.message+'。'+keepServiceOpen()+'请重新连接或重试取消。',true);}}}
async function relink(id,file){if(!project||!file||busy)return;const generation=++audioGeneration,offset=project.source.offset,clipDuration=project.source.clipDuration;try{if(file.size>104857600)throw Error('音频超过 100 MB 上限。');if(!/\.wav$/i.test(file.name))throw Error('重连请使用 WAV，这样分轨导出能保留原始 WAV 字节。');const url=URL.createObjectURL(file),ctx=audioContext();let buffer;try{buffer=await ctx.decodeAudioData(await file.arrayBuffer());}catch(e){URL.revokeObjectURL(url);throw Error('浏览器无法解码这个音频，请选择 WAV。');}if(generation!==audioGeneration){URL.revokeObjectURL(url);return;}if(Math.abs(buffer.duration-clipDuration)>.1){URL.revokeObjectURL(url);throw Error('音频时长与分析片段不一致。请选择与分析片段起点、长度相同的分轨 WAV，而不是整首原曲。');}stop();objectUrls.push(url);refs.set(id,{url,offset});decoded.set(id,buffer);render();status('已在当前页面连接'+(id==='original'?'原始片段':labels[id])+'音频。JSON 仍不包含音频，请单独保留 WAV。');}catch(e){status(e.message,true);}}
function saveProject(){if(!project)return;try{download(T.serializeProject(project),safeName()+'.transcription.json','application/json');dirty=false;status('识别工程 JSON 已生成，保留全部音符、音色、音效与分析数据。它不包含音频；请另外保存原始分轨 WAV。');}catch(e){status(e.message,true);}}
async function openProject(file){if(!file)return;if(busy)return status('当前任务还在运行，请先取消或等待完成。',true);try{if(file.size>T.MAX_JSON_BYTES)throw Error('工程文件过大。');const clean=T.parseProject(await file.text());if(!confirmReplace())return;replaceProject(clean);$('trKeepDrums').checked=false;status('识别工程已打开，音符与音效可继续编辑。JSON 不含音频，需要原音对比时请重连对应 WAV。数字作曲工程未改变。');}catch(e){status('无法打开：'+e.message,true);}}
function requestHandoff(){try{const r=range();pendingHandoff=T.toComposerProject(project,r);$('trHandoffText').textContent='将 '+r.start.toFixed(3)+'–'+r.end.toFixed(3)+' 秒发送为 '+pendingHandoff.tracks.length+' 条简谱轨道，并替换当前数字作曲工程“'+S.getProject().title+'”。请先保存当前简谱。识别工程会保留。\n'+(pendingHandoff.conversionWarnings||[]).join('\n');$('trHandoff').hidden=false;$('trHandoff').scrollIntoView?.({behavior:'smooth',block:'center'});}catch(e){pendingHandoff=null;$('trHandoff').hidden=true;status('无法送入简谱：'+e.message+'\n可以继续在这里精确编辑，或导出完整 MIDI 后进入高级作曲。',true);}}
for(const instrument of A.instruments){if(instrument.id!=='percussion'&&!T.INSTRUMENTS.includes(instrument.id))continue;const o=node('option',instrument.name);o.value=instrument.id;$('trInstrument').append(o);}const auto=node('option','使用估计 / 默认调性');auto.value='';$('trKey').append(auto);StudioCore.KEYS.forEach((key,i)=>{for(const mode of ['major','minor']){const o=node('option',key+(mode==='major'?' 大调':' 小调'));o.value=i+':'+mode;$('trKey').append(o);}});
$('trInputMode').onchange=()=>{$('trMixedInput').hidden=$('trInputMode').value!=='mix';$('trStemInputs').hidden=$('trInputMode').value!=='stems';$('trStart').textContent=$('trInputMode').value==='mix'?'开始分轨与识别':'识别已分轨音频';};$('trAudioFile').onchange=()=>{const f=$('trAudioFile').files[0];$('trFileLabel').textContent=f?f.name+' · '+(f.size/1048576).toFixed(1)+' MB':'还没有选择音频';};$('trCheckService').onclick=checkService;$('trStart').onclick=startJob;$('trCancel').onclick=cancelJob;$('trResume').onclick=()=>{if(!busy||!jobId)return;$('trResume').hidden=true;continueJobs(true);};
$('trTitle').onchange=e=>mutate(p=>{p.title=e.target.value;});$('trBpm').onchange=e=>mutate(p=>{p.overrides.bpm=e.target.value===''?null:Number(e.target.value);});$('trKey').onchange=e=>mutate(p=>{if(!e.target.value)p.overrides.key=null;else{const [tonic,mode]=e.target.value.split(':');p.overrides.key={tonic:Number(tonic),mode};}});$('trClearOverrides').onclick=()=>mutate(p=>{p.overrides={bpm:null,key:null};});$('trInstrument').onchange=e=>mutate(p=>{p.stems.find(s=>s.id===selectedStem).instrument=e.target.value;});$('trVolume').onchange=e=>mutate(p=>{p.stems.find(s=>s.id===selectedStem).volume=Number(e.target.value);});$('trMute').onchange=e=>mutate(p=>{p.stems.find(s=>s.id===selectedStem).mute=e.target.checked;});$('trSolo').onchange=e=>mutate(p=>{p.stems.find(s=>s.id===selectedStem).solo=e.target.checked;});
function editedNote(){const e={onset:Number($('trOnset').value),end:Number($('trEnd').value),midiPitch:Number($('trPitch').value),velocity:Number($('trVelocity').value)};if(e.onset<project.source.offset)throw Error('音符不能早于分析片段起点。');return e;}
$('trApplyNote').onclick=()=>{if(!selectedNote)return;mutate(p=>{const e=p.stems.find(s=>s.id===selectedStem).events.find(e=>e.id===selectedNote);Object.assign(e,editedNote());});};$('trAddNote').onclick=()=>{if(!project||selectedStem==='drums')return;mutate(p=>{const e=editedNote();e.id=uid(selectedStem);e.sourceStem=selectedStem;e.modelScore=null;e.original={onset:e.onset,end:e.end,midiPitch:e.midiPitch,velocity:e.velocity};p.stems.find(s=>s.id===selectedStem).events.push(e);selectedNote=e.id;});};$('trDeleteNote').onclick=()=>{if(!selectedNote)return;mutate(p=>{const s=p.stems.find(s=>s.id===selectedStem);s.events=s.events.filter(e=>e.id!==selectedNote);selectedNote=null;});};$('trQuantize').onclick=()=>{if(!project||busy)return;if(!window.confirm('将所有声部的音符起止时间对齐到 '+$('trGrid').selectedOptions[0].textContent+' 网格，使用当前 '+T.effectiveBpm(project)+' BPM。原始识别时间保留，可撤销。继续？'))return;try{const q=T.quantizeProject(project,Number($('trGrid').value));mutate(p=>{p.stems=q.stems;});status('已明确对齐全部音符到节拍网格。原始识别时间仍保留，可撤销。');}catch(e){status(e.message,true);}};$('trPrevPage').onclick=()=>{page--;renderNotes();};$('trNextPage').onclick=()=>{page++;renderNotes();};for(const id of ['trPreviewStart','trPreviewEnd'])$(id).onchange=()=>{stop();pendingHandoff=null;$('trHandoff').hidden=true;drawTimeline();};
$('trPlayOriginal').onclick=()=>playRaw('original');$('trPlayStem').onclick=()=>playRaw(selectedStem);$('trPlayNotes').onclick=()=>playNotes(false);$('trExportWav').onclick=()=>playNotes(true);$('trStop').onclick=stop;$('trKeepDrums').onchange=stop;$('trRelinkStem').onchange=e=>relink(selectedStem,e.target.files[0]);$('trRelinkOriginal').onchange=e=>relink('original',e.target.files[0]);$('trDownloadStem').onclick=async()=>{const id=selectedStem;try{const ref=refs.get(id);if(!ref)throw Error('当前轨原音未连接。');const r=await fetch(ref.url);if(!r.ok)throw Error('原分轨已失效，请重连保存的 WAV。');const blob=await r.blob();download(blob,safeName()+'-'+id+'-原始分轨.wav','audio/wav');status('已导出'+labels[id]+'原始分轨音频，没有换音色或改动音符。');}catch(e){status(e.message,true);}};
$('trGoSfx').onclick=()=>{S.showWorkspace('sfx');document.getElementById('notice').textContent='调整好音效后，回到“音频识别”添加当前音效。';};$('trAddSfx').onclick=()=>mutate(p=>{const onset=Number($('trSfxOnset').value);if(onset<p.source.offset)throw Error('音效不能早于分析片段起点。');p.sfxEvents.push({id:uid('sfx'),onset,params:S.getProject().sfx});});$('trUndo').onclick=()=>undo(false);$('trRedo').onclick=()=>undo(true);$('trSave').onclick=saveProject;$('trSaveBottom').onclick=saveProject;for(const id of ['trOpen','trOpenEmpty'])$(id).onclick=()=>{$('trProjectFile').value='';$('trProjectFile').click();};$('trProjectFile').onchange=e=>openProject(e.target.files[0]);$('trExportMidi').onclick=()=>{try{download(T.toMidi(project),safeName()+'.mid','audio/midi');status('完整多轨 MIDI 已生成（含全部可听声部的音符，保留原曲绝对时间；未识别的前段会为空白）。静音 / 非独奏声部、鼓音频与音效不进入 MIDI。');}catch(e){status(e.message,true);}};$('trToComposer').onclick=requestHandoff;$('trCancelHandoff').onclick=()=>{pendingHandoff=null;$('trHandoff').hidden=true;};$('trConfirmHandoff').onclick=()=>{if(!pendingHandoff)return;try{S.importProject(pendingHandoff);pendingHandoff=null;$('trHandoff').hidden=true;S.showWorkspace('music');$('notice').textContent='已送入数字作曲；原简谱可用撤销恢复，识别工程仍在“音频识别”保留。';}catch(e){status('没有替换简谱：'+e.message,true);}};$('trToAdvanced').onclick=()=>{S.showWorkspace('advanced');$('notice').textContent='先回音频识别导出完整 MIDI，再打开高级作曲 → 文件 → 导入歌曲。高级歌曲会被替换，请先保存。鼓音频、音效和采样不会随 MIDI 转入。';};
window.addEventListener('studio:workspace',e=>{stop();if(e.detail.tab!=='transcription'){pendingHandoff=null;$('trHandoff').hidden=true;}if(e.detail.tab==='transcription'){$('notice').textContent='从音频得到的是待校正草稿。原简谱、识别工程、高级歌曲分别保存，不会自动互相替换。';if(project)drawTimeline();}});window.addEventListener('beforeunload',e=>{stop();if(dirty||busy){e.preventDefault();e.returnValue='';}});document.addEventListener('keydown',e=>{if($('transcriptionPanel').hidden||!(e.ctrlKey||e.metaKey))return;if(e.key.toLowerCase()==='s'){e.preventDefault();saveProject();}else if(!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();undo(e.shiftKey||e.key.toLowerCase()==='y');}});
window.TranscriptionUI={getProject:()=>project?copy(project):null,getState:()=>({busy,ready,jobId,dirty,selectedStem,audioIds:Array.from(refs.keys())}),importProject:p=>replaceProject(p),acceptResult:r=>{mergeResults([r]);},openProject,checkService,startJob,cancelJob,stop,renderEdited,selectNote};
if(window.QiyinDesktop){const steps=$('trSetupHelp').querySelectorAll('li');steps[0].textContent='数字作曲与音效实验室已内置在七音客户端，可以直接使用。';steps[1].textContent='音频识别：点窗口顶部“准备音频识别”，确认后下载本地组件与模型。首次需要联网，建议至少 6 GB 可用空间、8 GB 内存。';steps[2].textContent='安装完成后在本页导入音频。处理期间保持客户端打开；模型留在本机，音频不会上传云端。';steps[3].textContent='若下载失败，查看窗口顶部的安装提示并重试；详细说明见随包“音频识别使用说明.txt”。';}checkService();S.showWorkspace('transcription');
})();
