'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {w}=require('./harness.cjs');let count=0;const tick=()=>new Promise(r=>setTimeout(r,0));
function test(name,fn){fn();count++;console.log('PASS '+name)}
const editor=w.testEditor,doc=editor.doc,B=w.beepbox,plain=x=>JSON.parse(JSON.stringify(x));
const expected=JSON.parse(fs.readFileSync(path.join(__dirname,'manifest.json')));
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const core=html.slice(html.indexOf('var beepbox='),html.indexOf('let qiyinHashWarning'));
const choose=value=>{let option=w.document.querySelector('option[value="'+value+'"]');assert(option,'option '+value);let select=option.parentElement;while(select.tagName!=='SELECT')select=select.parentElement;select.value=value;select.dispatchEvent(new w.Event('change',{bubbles:true}));};
const prompts=['export','import','songRecovery','barCount','beatsPerBar','moveNotesSideways','channelSettings','layout','recordingSetup','stringSustain','scale','key','tempo','reverb','rhythm','instrumentIndex','instrumentVolume','pan','instrumentType','eqFilter','noteFilter','fadeInOut','transition','chipWave','chipNoise','supersawDynamism','supersawSpread','supersawShape','pulseWidth','unison','chords','vibrato','algorithm','feedbackType','feedbackVolume','operatorFrequency','operatorVolume','spectrum','harmonics','effects','drumsetEnvelope','drumsetSpectrum','chorus','echoSustain','echoDelay','pitchShift','detune','distortion','bitcrusherQuantization','bitcrusherFreq','envelopes'];
(async()=>{
test('pinned native offline core hash is unchanged',()=>assert.equal(crypto.createHash('sha256').update(core).digest('hex'),expected.native_core_sha256));
test('all menus translated, original option values preserved',()=>{assert.equal(w.document.documentElement.lang,'zh-CN');for(const [v,t] of [['import','导入歌曲'],['export','导出歌曲'],['channelSettings','音轨设置'],['copyInstrument','复制音色']])assert(w.document.querySelector('option[value="'+v+'"]').textContent.includes(t));assert.equal(B.Config.scales[0].name,'easy :)');assert.equal(B.Config.effectNames[0],'reverb');});
test('all preset labels translated without changing preset IDs',()=>{for(const option of w.document.querySelectorAll('.instrument-settings option,select option')){if(!/^[0-9]+$/.test(option.value))continue;if(/[A-Za-z]{3}/.test(option.textContent)&&!/[\u4e00-\u9fff]/.test(option.textContent))assert.match(option.textContent,/^(?:Wicki-Hayden|FM|PWM)$/);}});
for(const name of prompts){editor.Uc(name);await tick();test('dynamic '+name+' dialog and help translated',()=>{const walker=w.document.createTreeWalker(editor.prompt.container,w.NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){const t=n.data.trim();if(/[A-Za-z]{3}/.test(t)&&!/[\u4e00-\u9fff]/.test(t))assert.match(t,/^(?:\.wav|\.mid|Wicki-Hayden|Imitone|Dubler)$/,'untranslated '+t);}const close=editor.prompt.container.querySelector('button.cancelButton');assert.equal(close.getAttribute('aria-label'),'关闭');});}
editor.Uc(null);
test('effect and instrument selectors retain original handlers',()=>{let before=doc.song.channels[0].instruments[0].preset;choose('randomPreset');assert.equal(typeof doc.song.channels[0].instruments[0].preset,'number');const fx=w.document.querySelector('.effects-menu select')||w.document.querySelector('select.effects-menu');assert(fx);const beforeEffects=doc.song.channels[0].instruments[0].effects;fx.value='9';fx.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal((doc.song.channels[0].instruments[0].effects^beforeEffects)&2,2);});
test('native channel insertion/deletion works',()=>{const n=doc.song.channels.length;doc.selection.insertChannel();assert.equal(doc.song.channels.length,n+1);doc.selection.deleteChannel();assert.equal(doc.song.channels.length,n);});
test('native bars and pattern actions work after translation',()=>{let bars=doc.song.barCount;doc.selection.insertBars();assert(doc.song.barCount>bars);doc.selection.deleteBars();assert.equal(doc.song.barCount,bars);doc.selection.setPattern(2);assert.equal(doc.song.channels[doc.channel].bars[doc.bar],2);});
const complex=new B.Song();complex.layeredInstruments=true;complex.patternInstruments=true;complex.tempo=137;complex.key=7;complex.scale=11;complex.loopStart=1;complex.loopLength=3;
for(let c=0;c<complex.channels.length;c++){const ch=complex.channels[c];let i=ch.instruments[0];i.setTypeAndReset(c===3?4:c===0?1:c===1?7:8,c===3);i.effects=4095;i.pan=c+1;i.pitchShift=8;i.detune=11;i.reverb=2;i.echoDelay=3;i.echoSustain=2;i.chorus=2;i.distortion=3;i.addEnvelope(0,0,1);ch.instruments.push(new B.Instrument(c===3));ch.patterns[0].instruments=[0,1];ch.patterns[0].notes=[new B.Note(c===3?2:24+c*7,0,24,3,c===3)];ch.patterns[0].notes[0].pins[1].interval=c===3?0:2;ch.bars[0]=1;ch.bars[1]=1;}
const json=complex.toJsonObject(true,1,true),canonical=new B.Song(JSON.stringify(json));
test('complex native JSON URL roundtrip preserves layered instruments, effects, envelope and bends',()=>{const j=canonical.toJsonObject(true,1,true);assert.deepEqual(plain(new B.Song(canonical.toBase64String()).toJsonObject(true,1,true)),plain(j));assert.equal(j.channels[0].instruments.length,2);assert.equal(j.channels[0].instruments[0].effects.length,12);assert.equal(j.channels[0].instruments[0].type,'FM');assert.equal(j.key,'G');assert.equal(j.channels[0].patterns[0].notes[0].points[1].pitchBend,2);assert.equal(j.layeredInstruments,true);});
test('localization never edits user file names or option values',()=>{editor.Uc('export');const input=editor.prompt.container.querySelector('input[type=text]');input.value='piano';const o=w.document.createElement('option');o.textContent='grand piano';editor.prompt.container.append(o);w.QiyinChinese.refresh();assert.equal(input.value,'piano');assert.equal(o.value,'grand piano');assert.equal(o.textContent,'三角钢琴');editor.Uc(null);});
editor.Uc('import');const importInput=editor.prompt.container.querySelector('input[type=file]');const source=JSON.stringify(canonical.toJsonObject(true,1,true));const file=new w.File([source],'中文工程.json',{type:'application/json'});file.text=async()=>source;Object.defineProperty(importInput,'files',{value:[file],configurable:true});importInput.dispatchEvent(new w.Event('change',{bubbles:true}));for(let i=0;i<20&&doc.song.tempo!==137;i++)await new Promise(r=>setTimeout(r,10));test('native JSON file import still uses original handler',()=>assert.equal(doc.song.tempo,137));editor.Uc(null);
const downloads=[];w.URL.createObjectURL=b=>{downloads.push(b);return 'blob:qa'};w.HTMLAnchorElement.prototype.click=function(){};const readBlob=blob=>new Promise((resolve,reject)=>{let r=new w.FileReader();r.onload=()=>resolve(Buffer.from(r.result));r.onerror=reject;r.readAsArrayBuffer(blob)});
doc.song=canonical;doc.synth.song=canonical;
for(const [fmt,type] of [['json','application/json'],['midi','audio/midi'],['html','text/html']]){editor.Uc('export');const p=editor.prompt;let select=p.container.querySelector('select');select.value=fmt;select.dispatchEvent(new w.Event('change',{bubbles:true}));p.container.querySelector('button.exportButton').click();await tick();test('native '+fmt+' export produces file',()=>{assert(downloads.length);assert.equal(downloads.at(-1).type,type)});const bytes=await readBlob(downloads.at(-1));if(fmt==='json')test('exported JSON reopens as native song',()=>assert.equal(new B.Song(bytes.toString()).tempo,137));if(fmt==='midi')test('native MIDI header retained',()=>assert.equal(bytes.subarray(0,4).toString(),'MThd'));editor.Uc(null);}
// Exercise real offline synthesis + WAV writer on a small song, not the audio hardware.
w.requestAnimationFrame=cb=>w.setTimeout(()=>cb(w.performance.now()),0);const short=new B.Song();short.barCount=1;short.loopStart=0;short.loopLength=1;short.beatsPerBar=3;short.tempo=300;for(const c of short.channels)c.bars.length=1;short.channels[0].patterns[0].notes=[new B.Note(36,0,12,3,false)];doc.song=short;doc.synth.song=short;editor.Uc('export');const exp=editor.prompt;await exp._h();exp.container.querySelectorAll('button.exportButton')[1].click();const wav=await readBlob(downloads.at(-1));test('native WAV offline synthesis remains functional',()=>{assert.equal(wav.subarray(0,4).toString(),'RIFF');assert.equal(wav.subarray(8,12).toString(),'WAVE');assert(wav.length>44);});
console.log(count+' native DOM/localization/model/export tests passed. No browser visual or Windows execution claim.');w.close();
})().catch(error=>{console.error(error);w.close();process.exitCode=1});
