(()=>{'use strict';const api=window.QiyinDesktop;if(!api)return;
const bar=document.createElement('section');bar.className='desktop-bar';bar.innerHTML='<strong>七音 · 桌面客户端</strong><span id="desktop-short">数字作曲、音效与高级作曲可直接使用</span><button id="desktop-open">准备音频识别</button>';
document.body.prepend(bar);
for(const li of document.querySelectorAll('#helpPanel li')){if(li.textContent.includes('双击 index.html'))li.textContent='请完整解压客户端文件夹，再双击“七音音乐工作室.exe”。无需手动打开浏览器或安装开发工具。';if(li.textContent.includes('导出文件位置由浏览器'))li.textContent='导出时可在系统保存窗口选择位置。WAV 为 44.1 kHz、16 位、单声道 PCM。';}
const panel=document.createElement('section');panel.className='desktop-setup';panel.hidden=true;panel.innerHTML='<div class="desktop-setup-heading"><h2>本机音频识别</h2><button id="desktop-close" aria-label="收起准备面板">收起</button></div><p id="desktop-explanation">正在检查本机识别组件…</p><p>组件与模型放在客户端旁的 .runtime 文件夹，不修改系统 PATH。建议 8 GB 内存并保留至少 2 GB 工作空间。音频和乐谱均在本机处理。</p><p id="desktop-state" role="status"></p><progress id="desktop-progress" max="1"></progress><div><button id="desktop-prepare">下载并准备识别组件</button> <button id="desktop-cancel" hidden>取消准备</button></div><details><summary>查看准备日志 / 错误详情</summary><pre id="desktop-log"></pre></details>';
bar.after(panel);const $=id=>document.getElementById(id);let wasReady=false;
function render(s){const offline=s.preparationMode==='offline';$('desktop-explanation').textContent=offline?'本更新已包含 Python、音频模型与依赖。启用时只校验本机文件并启动，不联网下载。校验失败请重新完整解压更新包。若系统缺少微软 C++ 运行库，按更新说明完成首次安装。':'普通作曲不需要下载。未检测到离线组件时，首次音频准备将从官方来源下载约 1–2 GB；需至少 6 GB 可用空间。';$('desktop-state').textContent=s.message;$('desktop-short').textContent=s.phase==='ready'?'本机音频识别已就绪':s.phase==='working'?'正在准备识别组件，作曲仍可使用':(offline?'作曲可直接使用 · 离线识别待启用':'作曲可直接使用 · 音频识别按需准备');$('desktop-log').textContent=(s.logs||[]).join('\n');$('desktop-prepare').disabled=s.phase==='working'||s.phase==='ready';$('desktop-prepare').textContent=s.phase==='error'?'重试校验 / 启动':offline?'启用内置识别组件':'下载并准备识别组件';$('desktop-cancel').hidden=s.phase!=='working';$('desktop-progress').hidden=s.phase!=='working';if(typeof s.progress==='number')$('desktop-progress').value=s.progress;else $('desktop-progress').removeAttribute('value');if(s.phase==='ready'&&!wasReady&&window.TranscriptionUI)window.TranscriptionUI.checkService();wasReady=s.phase==='ready';}
$('desktop-open').onclick=()=>panel.hidden=!panel.hidden;$('desktop-close').onclick=()=>panel.hidden=true;
$('desktop-prepare').onclick=async()=>{try{await api.prepare();}catch(e){$('desktop-state').textContent=e.message;}};$('desktop-cancel').onclick=async()=>{try{await api.cancel();}catch(e){$('desktop-state').textContent=e.message;}};
api.onStatus(render);api.onOpen(()=>{panel.hidden=false;panel.scrollIntoView({behavior:'smooth'});});api.status().then(render);})();
