'use strict';
const fs=require('node:fs'),fsp=fs.promises,path=require('node:path'),https=require('node:https'),http=require('node:http'),crypto=require('node:crypto'),net=require('node:net');
const {spawn}=require('node:child_process');
const {OfflineAudioBundle}=require('./offline-audio.cjs');
const UV_URL='https://github.com/astral-sh/uv/releases/download/0.12.23/uv-x86_64-pc-windows-msvc.zip';
const UV_HASH='75d05de6762778c31ee183398de7dd15093fad0ed90b1f236d8205ea5ec00c90';
const DOWNLOAD_HOSTS=new Set(['github.com','release-assets.githubusercontent.com','objects.githubusercontent.com']);
class SetupManager{
 constructor({root,runtime,token,notify}){this.root=root;this.runtime=runtime;this.token=token;this.notify=notify;this.offline=new OfflineAudioBundle(runtime);this._runMode=null;this.backend=null;this.backendPort=null;this.child=null;this.request=null;this.cancelled=false;this.active=false;this.state={preparationMode:this.preparationMode,phase:'idle',message:this.hasOfflineBundle?'普通作曲已可使用；离线音频组件可在本机校验后启用。':'普通作曲已可使用；音频识别组件按需下载。',logs:[]};}
 update(patch){Object.assign(this.state,patch,{preparationMode:this.preparationMode});this.notify({...this.state,logs:[...this.state.logs]});}
 log(text){const lines=String(text).replace(/\x1b\[[0-9;]*[A-Za-z]/g,'').split(/[\r\n]+/).filter(Boolean);this.state.logs.push(...lines.map(x=>x.slice(0,1000)));this.state.logs=this.state.logs.slice(-100);this.update({});}
 get hasOfflineBundle(){if(this.offline.present)this._sawOfflineBundle=true;return !!this._sawOfflineBundle;}
 get preparationMode(){return (this.active||this.backend)&&this._runMode?this._runMode:(this.hasOfflineBundle?'offline':'online');}
 get python(){return this.preparationMode==='offline'?this.offline.python:path.join(this.runtime,'venv','Scripts','python.exe');}
 get modelDir(){return this.preparationMode==='offline'?this.offline.modelDir:path.join(this.runtime,'models');}
 get fingerprint(){if(this.preparationMode==='offline'){const trusted=this.offline.inspectSync(),digest=crypto.createHash('sha256').update('audio-offline-v1\0').update(path.resolve(this.runtime)).update('\0'+trusted.manifestSha256);for(const file of ['launcher/windows-requirements.lock.txt','launcher/windows-overrides.txt','local_service/requirements.txt','local_service/setup_models.py','local_service/server.py','local_service/pipeline.py'])digest.update('\0'+file+'\0').update(fs.readFileSync(path.join(this.root,file)));return digest.digest('hex');}return crypto.createHash('sha256').update(this.runtime.toLowerCase()).update(fs.readFileSync(path.join(this.root,'launcher','windows-requirements.lock.txt'))).update(fs.readFileSync(path.join(this.root,'launcher','windows-overrides.txt'))).update(fs.readFileSync(path.join(this.root,'local_service','setup_models.py'))).digest('hex');}
 isInstalled(){try{if(this.preparationMode==='offline')return this.offline.isReady(this.fingerprint);return JSON.parse(fs.readFileSync(this.marker,'utf8')).fingerprint===this.fingerprint&&fs.existsSync(this.python);}catch{return false;}}
 get marker(){return this.preparationMode==='offline'?this.offline.marker:path.join(this.runtime,'ready-desktop-v1.json');}
 get env(){const env={...process.env,UV_CACHE_DIR:path.join(this.runtime,'cache'),UV_PYTHON_INSTALL_DIR:path.join(this.runtime,'python'),UV_PYTHON_INSTALL_BIN:'0',UV_NO_MODIFY_PATH:'1',UV_PYTHON_PREFERENCE:'only-managed',PYTHONNOUSERSITE:'1',PYTHONUTF8:'1',PYTHONUNBUFFERED:'1',PYTHONDONTWRITEBYTECODE:'1',ORT_DISABLE_TELEMETRY:'1',STUDIO_API_TOKEN:this.token,STUDIO_MODEL_DIR:this.modelDir,TF_CPP_MIN_LOG_LEVEL:'2',DO_NOT_TRACK:'1'};for(const key of Object.keys(env))if(/^PYTHON/i.test(key)&&!['PYTHONNOUSERSITE','PYTHONUTF8','PYTHONUNBUFFERED','PYTHONDONTWRITEBYTECODE'].includes(key))delete env[key];if(this.preparationMode==='offline'){for(const key of Object.keys(env))if(/^(?:IMAGEIO_FFMPEG_EXE|STUDIO_FFMPEG_EXE)$/i.test(key))delete env[key];Object.assign(env,{IMAGEIO_FFMPEG_EXE:this.offline.ffmpeg,STUDIO_FFMPEG_EXE:this.offline.ffmpeg,UV_OFFLINE:'1',PIP_NO_INDEX:'1',HF_HUB_OFFLINE:'1',TRANSFORMERS_OFFLINE:'1',NUMBA_CACHE_DIR:path.join(this.offline.cacheDir,'numba'),LIBROSA_CACHE_DIR:path.join(this.offline.cacheDir,'librosa'),LIBROSA_CACHE_LEVEL:'10'});delete env.VIRTUAL_ENV;delete env.CONDA_PREFIX;}return env;}
 checkCancel(){if(this.cancelled)throw Object.assign(Error('准备已取消。已有组件文件会保留，下次可重试。'),{code:'SETUP_CANCELLED'});}
 assertSupportedPlatform(){if(process.platform!=='win32'||process.arch!=='x64')throw Error('此版本仅支持 Windows 10/11 x64。');}
 run(exe,args,{timeout=30*60*1000}={}){this.checkCancel();return new Promise((resolve,reject)=>{const child=spawn(exe,args,{cwd:this.root,env:this.env,windowsHide:true,shell:false});this.child=child;let done=false;const timer=setTimeout(()=>{this.killTree(child);finish(Error(this.preparationMode==='offline'?'本机组件自检超时，请查看日志后重试。':'本步骤超时，请检查网络后重试。'));},timeout);const finish=err=>{if(done)return;done=true;clearTimeout(timer);if(this.child===child)this.child=null;err?reject(err):resolve();};child.stdout.on('data',x=>this.log(x));child.stderr.on('data',x=>this.log(x));child.once('error',finish);child.once('exit',code=>finish(this.cancelled?Object.assign(Error('准备已取消。已有组件文件会保留，下次可重试。'),{code:'SETUP_CANCELLED'}):code===0?null:Error('组件准备失败（退出码 '+code+'）。请查看下方日志。')));});}
 killTree(child){if(!child||!child.pid)return;if(process.platform==='win32'){spawn(path.join(process.env.SystemRoot||'C:\\Windows','System32','taskkill.exe'),['/PID',String(child.pid),'/T','/F'],{windowsHide:true,shell:false}).on('error',()=>child.kill());}else child.kill('SIGTERM');}
 download(url,destination,redirects=0){this.checkCancel();if(this.preparationMode==='offline')return Promise.reject(Error('离线准备不允许联网下载。请使用完整的离线更新包。'));return new Promise((resolve,reject)=>{const parsed=new URL(url);if(parsed.protocol!=='https:'||!DOWNLOAD_HOSTS.has(parsed.hostname)||redirects>5)return reject(Error('下载地址不在官方允许范围内。'));let finished=false;const fail=error=>{if(finished)return;finished=true;reject(error);};const request=https.get(url,{headers:{'User-Agent':'QiyinMusicStudio/1.0'}},response=>{if([301,302,303,307,308].includes(response.statusCode)){response.resume();if(!response.headers.location)return fail(Error('下载重定向缺少地址。'));finished=true;return this.download(new URL(response.headers.location,url).href,destination,redirects+1).then(resolve,reject);}if(response.statusCode!==200){response.resume();return fail(Error('官方下载服务返回 '+response.statusCode+'，请稍后重试。'));}const out=fs.createWriteStream(destination),digest=crypto.createHash('sha256');let total=0,last=0;const expected=Number(response.headers['content-length'])||0;response.on('data',chunk=>{total+=chunk.length;if(total>100*1024*1024){request.destroy(Error('运行时下载超过安全上限。'));return;}digest.update(chunk);if(Date.now()-last>500){last=Date.now();this.update({message:'下载运行时管理器：'+(total/1048576).toFixed(1)+' MB'+(expected?' / '+(expected/1048576).toFixed(1)+' MB':''),progress:expected?Math.min(.15,total/expected*.15):undefined});}});response.on('error',e=>{out.destroy();fail(e);});out.on('error',e=>{request.destroy();fail(e);});out.on('finish',()=>{if(finished)return;finished=true;resolve(digest.digest('hex'));});response.pipe(out);});this.request=request;request.setTimeout(45000,()=>request.destroy(Error('下载连接超时，请检查网络后重试。')));request.on('error',fail);});}
 async prepare(){if(this.active)return;this._runMode=this.hasOfflineBundle?'offline':'online';this.active=true;this.cancelled=false;this.update({phase:'working',message:'正在检查本机组件…',progress:0,logs:[]});try{
 this.assertSupportedPlatform();
 if(this.preparationMode==='offline'){await this.prepareOffline();return;}
 await fsp.mkdir(this.runtime,{recursive:true});await fsp.access(this.runtime,fs.constants.W_OK);
 let installed=false;try{installed=JSON.parse(await fsp.readFile(this.marker,'utf8')).fingerprint===this.fingerprint&&fs.existsSync(this.python);}catch{}
 if(!installed){
 const disk=await fsp.statfs(this.runtime);if(Number(disk.bavail)*Number(disk.bsize)<6*1024**3)throw Error('客户端所在磁盘可用空间不足 6 GB，请移到空间充足的文件夹。');
 await fsp.mkdir(path.join(this.runtime,'cache'),{recursive:true});const uv=path.join(this.runtime,'uv.exe');if(!fs.existsSync(uv)){
 this.update({message:'第 1/4 步：下载官方运行时管理器…',progress:0});const zip=path.join(this.runtime,'uv-download.zip');const digest=await this.download(UV_URL,zip);if(digest!==UV_HASH){await fsp.rm(zip,{force:true});throw Error('运行时下载 SHA256 校验失败，已停止。');}this.checkCancel();
 const powershell=path.join(process.env.SystemRoot||'C:\\Windows','System32','WindowsPowerShell','v1.0','powershell.exe');
 const script="$ErrorActionPreference='Stop'; $zip=Join-Path $env:UV_CACHE_DIR '..\\uv-download.zip'; $out=Join-Path $env:UV_CACHE_DIR '..\\uv-unpack'; Expand-Archive -LiteralPath $zip -DestinationPath $out -Force; $exe=Get-ChildItem -LiteralPath $out -Filter uv.exe -Recurse | Select-Object -First 1; if(!$exe){throw 'Missing official uv.exe'}; Copy-Item -LiteralPath $exe.FullName -Destination (Join-Path $env:UV_CACHE_DIR '..\\uv.exe');";
 await this.run(powershell,['-NoLogo','-NoProfile','-NonInteractive','-Command',script],{timeout:120000});await fsp.rm(zip,{force:true});}
 this.update({message:'第 2/4 步：准备独立 Python 3.11.16…',progress:.18});await this.run(uv,['--no-config','python','install','3.11.16','--no-bin']);await this.run(uv,['--no-config','venv','--allow-existing','--python','3.11.16',path.join(this.runtime,'venv')]);
 this.update({message:'第 3/4 步：下载并校验本机识别依赖（较大下载请耐心等待）…',progress:.3});await this.run(uv,['--no-config','pip','install','--python',this.python,'--index-url','https://pypi.org/simple','--require-hashes','--only-binary',':all:','--override',path.join(this.root,'launcher','windows-overrides.txt'),'-r',path.join(this.root,'launcher','windows-requirements.lock.txt')]);
 this.update({message:'第 4/4 步：下载并校验官方分轨模型…',progress:.8});await this.run(this.python,[path.join(this.root,'local_service','setup_models.py')]);
 await this.run(this.python,['-c','import tensorflow, basic_pitch, spleeter, imageio_ffmpeg; print("本机识别组件检查完成")'],{timeout:180000});
 await fsp.writeFile(this.marker,JSON.stringify({version:1,fingerprint:this.fingerprint,python:'3.11.16',uv:'0.12.23',created:new Date().toISOString()}));
 }
 this.checkCancel();await this.startBackend();this.update({phase:'ready',message:'本机识别已就绪。可以断网使用，音频只在本机处理。',progress:1});
 }catch(error){await this.stopBackend();this.update({phase:this.cancelled?'idle':'error',message:this.cancelled?'已取消准备。已有作曲功能仍可使用。':error.message,progress:undefined});this.log(error.message);}finally{this.active=false;this.child=null;this.request=null;}}
 async prepareOffline(){
 await fsp.access(this.runtime,fs.constants.W_OK);let lastProgress=0;
 this.update({message:'第 1/3 步：校验完整离线 Python、依赖与四轨模型（无需联网）…',progress:0});
 const verified=await this.offline.verify({checkCancel:()=>this.checkCancel(),onProgress:status=>{if(Date.now()-lastProgress>150||status.verifiedFiles===status.totalFiles){lastProgress=Date.now();this.update({message:'第 1/3 步：校验离线组件 '+(status.verifiedBytes/1048576).toFixed(0)+' / '+(status.totalBytes/1048576).toFixed(0)+' MB…',progress:status.totalBytes?status.verifiedBytes/status.totalBytes*.75:0});}}});
 this.checkCancel();await this.offline.prepareCache(()=>this.checkCancel());const fingerprint=this.fingerprint;
 // Full integrity validation and native imports repeat on every start; the
 // marker never bypasses them or masks a removed system VC++ runtime.
 this.update({message:'第 2/3 步：检查本机识别依赖（无需联网）…',progress:.78});
 try{await this.run(this.python,['-s','-c','import onnxruntime; onnxruntime.disable_telemetry_events(); import tensorflow, basic_pitch, spleeter, imageio_ffmpeg, soundfile, librosa, psutil; print("离线识别组件导入检查完成")'],{timeout:180000});}
 catch(error){this.checkCancel();throw Error('离线依赖自检失败。请查看日志中的具体错误；如提示 DLL load failed / MSVCP140 / VCRUNTIME140，请自行安装 Microsoft 官方 Visual C++ x64 离线运行库后重试（更新包中如有安装程序可直接使用）。无需下载 Python 或模型。原始错误：'+error.message);}
 this.checkCancel();this.update({message:'第 3/3 步：检查本机识别服务…',progress:.9});await this.startBackend();this.checkCancel();
 const temporary=this.offline.marker+'.'+crypto.randomBytes(8).toString('hex')+'.tmp';
 try{await fsp.writeFile(temporary,JSON.stringify({version:1,fingerprint,manifestSha256:verified.manifestSha256,files:verified.files,bytes:verified.bytes,created:new Date().toISOString()}),{flag:'wx',mode:0o600});this.checkCancel();await fsp.rename(temporary,this.offline.marker);}finally{await fsp.rm(temporary,{force:true});}
 this.checkCancel();this.update({phase:'ready',message:'离线音频识别已就绪。准备与识别均无需联网，音频只在本机处理。',progress:1});
 }
 health(){return new Promise((resolve,reject)=>{const request=http.get({hostname:'127.0.0.1',port:this.backendPort,path:'/api/health',headers:{'X-Studio-Token':this.token}},res=>{let data='';res.on('data',x=>data+=x);res.on('end',()=>{try{resolve(JSON.parse(data));}catch(e){reject(e);}});});request.setTimeout(2000,()=>request.destroy());request.on('error',reject);});}
 async startBackend(){if(this.backend){try{const h=await this.health();if(h.ready)return;}catch{}await this.stopBackend();}this.update({message:'正在启动本机识别服务…',progress:.95});this.backendPort=await new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});
 const child=spawn(this.python,[path.join(this.root,'local_service','server.py'),'--port',String(this.backendPort)],{cwd:this.root,env:this.env,windowsHide:true,shell:false});this.backend=child;child.stdout.on('data',x=>this.log(x));child.stderr.on('data',x=>this.log(x));let exited=false;child.once('error',e=>{exited=true;this.log(e.message);});child.once('exit',()=>{exited=true;if(this.backend===child){this.backend=null;this.backendPort=null;if(this.state.phase==='ready')this.update({phase:'error',message:'本机识别服务已停止。请点“重试准备 / 启动”。'});}});
 const until=Date.now()+90000;while(Date.now()<until){this.checkCancel();if(exited)throw Error('本机识别服务启动失败，请查看日志。');try{const h=await this.health();if(h.ready)return;if(h.missing?.length)throw Object.assign(Error('本机组件不完整：'+h.missing.join('、')+'。请重试准备。'),{incomplete:true});}catch(e){if(e.incomplete){await fsp.rm(this.marker,{force:true});throw e;}}await new Promise(r=>setTimeout(r,500));}await this.stopBackend();throw Error('识别服务启动超时。请检查日志或重试。');}
 async stopBackend(){const child=this.backend,port=this.backendPort;this.backend=null;this.backendPort=null;if(!child)return;await new Promise(resolve=>{const request=http.request({hostname:'127.0.0.1',port,path:'/api/shutdown',method:'POST',headers:{'X-Studio-Token':this.token,'Content-Length':'0','Origin':'http://127.0.0.1:'+port}},r=>{r.resume();r.on('end',resolve);});request.setTimeout(1500,()=>{request.destroy();resolve();});request.on('error',resolve);request.end();});if(child.exitCode!==null)return;await Promise.race([new Promise(r=>child.once('exit',r)),new Promise(r=>setTimeout(r,10000))]);if(child.exitCode===null)this.killTree(child);}
 async cancel(){if(!this.active)return;this.cancelled=true;if(this.request)this.request.destroy(Error('用户取消准备'));if(this.child)this.killTree(this.child);await this.stopBackend();}
}
module.exports={SetupManager,UV_URL,UV_HASH};
